import json

# ====== ACSM / 运动科学 / 运动康复 1000词专业词库 ======
# 按领域分类，每个词带准确中文翻译、难度分级、频率权重

# 领域1: 运动生理学基础 (~125词)
physiology = [
    ("physiology", ["生理学"], 8, "medium"),
    ("homeostasis", ["稳态", "内环境稳定"], 6, "hard"),
    ("metabolism", ["代谢"], 9, "medium"),
    ("anabolic", ["合成的", "同化作用的"], 5, "hard"),
    ("catabolic", ["分解的", "异化作用的"], 5, "hard"),
    ("aerobic", ["有氧的"], 10, "easy"),
    ("anaerobic", ["无氧的"], 9, "medium"),
    ("glycolysis", ["糖酵解"], 7, "hard"),
    ("oxidative", ["氧化的"], 6, "hard"),
    ("phosphorylation", ["磷酸化"], 5, "hard"),
    ("mitochondria", ["线粒体"], 6, "hard"),
    ("myoglobin", ["肌红蛋白"], 5, "hard"),
    ("hemoglobin", ["血红蛋白"], 6, "medium"),
    ("oxygen", ["氧气"], 10, "easy"),
    ("carbon", ["碳"], 7, "easy"),
    ("dioxide", ["二氧化碳"], 7, "medium"),
    ("ventilation", ["通气", "通风"], 7, "hard"),
    ("respiration", ["呼吸", "呼吸作用"], 8, "medium"),
    ("diffusion", ["扩散"], 6, "medium"),
    ("perfusion", ["灌注"], 5, "hard"),
    ("saturation", ["饱和度"], 6, "medium"),
    ("hypoxia", ["缺氧"], 5, "hard"),
    ("hyperoxia", ["高氧"], 4, "hard"),
    ("hypoxemia", ["低氧血症"], 4, "hard"),
    ("lactate", ["乳酸"], 8, "medium"),
    ("threshold", ["阈值", "临界点"], 8, "medium"),
    ("onset", [" onset", "起始"], 6, "medium"),
    ("acidosis", ["酸中毒"], 5, "hard"),
    ("alkalosis", ["碱中毒"], 4, "hard"),
    ("buffer", ["缓冲"], 5, "medium"),
    ("enzyme", ["酶"], 7, "medium"),
    ("catalyst", ["催化剂"], 4, "hard"),
    ("hormone", ["激素"], 8, "medium"),
    ("insulin", ["胰岛素"], 7, "medium"),
    ("glucagon", ["胰高血糖素"], 5, "hard"),
    ("cortisol", ["皮质醇"], 6, "hard"),
    ("epinephrine", ["肾上腺素"], 6, "hard"),
    ("norepinephrine", ["去甲肾上腺素"], 5, "hard"),
    ("testosterone", ["睾酮"], 7, "hard"),
    ("estrogen", ["雌激素"], 6, "hard"),
    ("growth", ["生长"], 8, "easy"),
    ("thermogenesis", ["产热"], 4, "hard"),
    ("substrate", ["底物", "基质"], 6, "hard"),
    ("glucose", ["葡萄糖"], 8, "medium"),
    ("glycogen", ["糖原"], 7, "hard"),
    ("fatty", ["脂肪的"], 6, "medium"),
    ("lipid", ["脂质"], 6, "hard"),
    ("triglyceride", ["甘油三酯"], 5, "hard"),
    ("cholesterol", ["胆固醇"], 6, "hard"),
    ("protein", ["蛋白质"], 9, "easy"),
    ("amino", ["氨基"], 5, "hard"),
    ("synthesis", ["合成"], 7, "hard"),
    ("degradation", ["降解"], 5, "hard"),
    ("calorie", ["卡路里", "千卡"], 8, "easy"),
    ("kilocalorie", ["千卡"], 6, "hard"),
    ("metabolic", ["代谢的"], 8, "medium"),
    ("rate", ["速率"], 9, "easy"),
    ("equivalent", ["当量"], 6, "hard"),
    ("vo2max", ["最大摄氧量"], 8, "hard"),
    ("vco2", ["二氧化碳排出量"], 5, "hard"),
    ("rer", ["呼吸交换率"], 5, "hard"),
    ("ventilatory", ["通气的"], 5, "hard"),
    ("anaerobic", ["无氧的"], 7, "medium"),
    ("atp", ["三磷酸腺苷"], 7, "hard"),
    ("adp", ["二磷酸腺苷"], 5, "hard"),
    ("phosphocreatine", ["磷酸肌酸"], 5, "hard"),
    ("kinase", ["激酶"], 4, "hard"),
    ("phosphofructokinase", ["磷酸果糖激酶"], 4, "hard"),
    ("cytochrome", ["细胞色素"], 4, "hard"),
    ("electron", ["电子"], 6, "medium"),
    ("transport", ["转运", "运输"], 7, "medium"),
    ("chain", ["链"], 6, "easy"),
    ("proton", ["质子"], 5, "hard"),
    ("gradient", ["梯度"], 5, "medium"),
    ("chemiosmosis", ["化学渗透"], 3, "hard"),
    ("condensation", ["缩合"], 4, "hard"),
    ("hydrolysis", ["水解"], 5, "hard"),
    ("neurotransmitter", ["神经递质"], 5, "hard"),
    ("acetylcholine", ["乙酰胆碱"], 5, "hard"),
    ("norepinephrine", ["去甲肾上腺素"], 5, "hard"),
    ("dopamine", ["多巴胺"], 5, "hard"),
    ("serotonin", ["血清素"], 5, "hard"),
    ("endorphin", ["内啡肽"], 5, "hard"),
    ("cytokine", ["细胞因子"], 5, "hard"),
    ("interleukin", ["白介素"], 4, "hard"),
    ("c-reactive", ["C反应蛋白"], 4, "hard"),
    ("antioxidant", ["抗氧化剂"], 6, "hard"),
    ("radical", ["自由基"], 5, "hard"),
    ("reactive", ["反应性的"], 5, "medium"),
    ("species", ["物种", "种类"], 6, "easy"),
    ("oxidative", ["氧化应激"], 6, "hard"),
    ("stress", ["应激"], 8, "easy"),
    ("inflammation", ["炎症"], 7, "hard"),
    ("anti-inflammatory", ["抗炎的"], 5, "hard"),
    ("immune", ["免疫的"], 7, "medium"),
    ("immunoglobulin", ["免疫球蛋白"], 4, "hard"),
    ("leukocyte", ["白细胞"], 5, "hard"),
    ("lymphocyte", ["淋巴细胞"], 5, "hard"),
    ("neutrophil", ["中性粒细胞"], 4, "hard"),
    ("monocyte", ["单核细胞"], 4, "hard"),
    ("macrophage", ["巨噬细胞"], 5, "hard"),
    ("eicosanoid", ["类花生酸"], 3, "hard"),
    ("prostaglandin", ["前列腺素"], 4, "hard"),
    ("leukotriene", ["白三烯"], 3, "hard"),
]

# 领域2: 肌肉骨骼解剖 (~140词)
anatomy = [
    ("anatomy", ["解剖学"], 7, "medium"),
    ("muscle", ["肌肉"], 10, "easy"),
    ("skeletal", ["骨骼的"], 8, "hard"),
    ("smooth", ["平滑的"], 6, "medium"),
    ("cardiac", ["心脏的"], 7, "medium"),
    ("striated", ["横纹的"], 4, "hard"),
    ("fiber", ["纤维"], 8, "easy"),
    ("fascicle", ["肌束"], 5, "hard"),
    ("fascia", ["筋膜"], 6, "hard"),
    ("tendon", ["肌腱"], 8, "medium"),
    ("ligament", ["韧带"], 7, "hard"),
    ("aponeurosis", ["腱膜"], 4, "hard"),
    ("sarcolemma", ["肌膜"], 4, "hard"),
    ("sarcoplasm", ["肌质"], 4, "hard"),
    ("sarcoplasmic", ["肌质的"], 4, "hard"),
    ("reticulum", ["网状组织"], 5, "hard"),
    ("myofibril", ["肌原纤维"], 5, "hard"),
    ("sarcomere", ["肌节"], 6, "hard"),
    ("actin", ["肌动蛋白"], 6, "hard"),
    ("myosin", ["肌球蛋白"], 6, "hard"),
    ("troponin", ["肌钙蛋白"], 5, "hard"),
    ("tropomyosin", ["原肌球蛋白"], 5, "hard"),
    ("titin", ["肌联蛋白"], 4, "hard"),
    ("dystrophin", ["抗肌萎缩蛋白"], 3, "hard"),
    ("motor", ["运动", " motor"], 9, "easy"),
    ("unit", ["单位"], 8, "easy"),
    ("neuromuscular", ["神经肌肉的"], 6, "hard"),
    ("junction", [" junction", "接合部"], 5, "medium"),
    ("endplate", ["终板"], 4, "hard"),
    ("axon", ["轴突"], 5, "hard"),
    ("dendrite", ["树突"], 4, "hard"),
    ("synapse", ["突触"], 5, "hard"),
    ("axon", ["轴突"], 5, "hard"),
    ("terminal", ["终末的"], 5, "medium"),
    ("vesicle", ["囊泡"], 4, "hard"),
    ("receptor", ["受体"], 7, "hard"),
    ("agonist", ["主动肌", "激动剂"], 7, "hard"),
    ("antagonist", ["拮抗肌", "拮抗剂"], 7, "hard"),
    ("synergist", ["协同肌"], 5, "hard"),
    ("stabilizer", ["稳定肌"], 5, "hard"),
    ("fixator", ["固定肌"], 4, "hard"),
    ("prime", ["主要的"], 6, "easy"),
    ("mover", ["原动肌"], 5, "medium"),
    ("contraction", ["收缩"], 9, "medium"),
    ("isometric", ["等长的"], 7, "hard"),
    ("isotonic", ["等张的"], 6, "hard"),
    ("isokinetic", ["等速的", "等动的"], 6, "hard"),
    ("concentric", ["向心的"], 7, "hard"),
    ("eccentric", ["离心的"], 7, "hard"),
    ("tetanic", ["强直的"], 4, "hard"),
    ("twitch", ["抽搐", "单收缩"], 5, "medium"),
    ("summation", ["总和"], 5, "hard"),
    ("recruitment", ["募集"], 6, "hard"),
    ("rate", ["频率"], 8, "easy"),
    ("coding", ["编码"], 5, "medium"),
    ("size", ["大小", "尺寸"], 7, "easy"),
    ("principle", ["原理"], 7, "easy"),
    ("henneman", ["亨尼曼"], 3, "hard"),
    ("threshold", ["阈值"], 6, "medium"),
    ("hypertrophy", ["肥大", "增生"], 8, "hard"),
    ("hyperplasia", ["增生"], 5, "hard"),
    ("atrophy", ["萎缩"], 6, "hard"),
    ("sarcopenia", ["肌少症"], 5, "hard"),
    ("myopathy", ["肌病"], 4, "hard"),
    ("neuropathy", ["神经病"], 5, "hard"),
    ("dystrophy", ["营养不良", " dystrophy"], 4, "hard"),
    ("fasciculation", ["肌束震颤"], 3, "hard"),
    ("cramp", ["痉挛"], 5, "easy"),
    ("spasm", ["痉挛"], 5, "medium"),
    ("strain", ["拉伤"], 6, "medium"),
    ("sprain", ["扭伤"], 6, "medium"),
    ("tear", ["撕裂"], 5, "medium"),
    ("rupture", ["破裂"], 5, "medium"),
    ("tendinopathy", ["肌腱病"], 5, "hard"),
    ("tendinosis", ["肌腱变性"], 4, "hard"),
    ("epicondylitis", ["上髁炎"], 4, "hard"),
    ("fasciitis", ["筋膜炎"], 4, "hard"),
    ("compartment", ["筋膜室"], 5, "hard"),
    ("syndrome", ["综合征"], 6, "medium"),
    (" DOMS", ["延迟性肌肉酸痛"], 6, "hard"),
    ("delayed", ["延迟的"], 6, "medium"),
    ("onset", [" onset"], 5, "medium"),
    ("soreness", ["酸痛"], 6, "medium"),
    ("lactic", ["乳酸的"], 6, "hard"),
    ("acid", ["酸"], 7, "easy"),
    ("oxygen", ["氧"], 8, "easy"),
    ("debt", [" debt", "亏欠"], 5, "medium"),
    ("deficit", [" deficit", "不足"], 5, "medium"),
    ("excess", ["过量"], 5, "medium"),
    ("post-exercise", ["运动后"], 5, "hard"),
    ("consumption", ["消耗"], 6, "medium"),
    ("epoc", ["运动后过量氧耗"], 5, "hard"),
    ("fast", ["快的"], 7, "easy"),
    ("slow", ["慢的"], 7, "easy"),
    ("oxidative", ["氧化型的"], 5, "hard"),
    ("glycolytic", ["酵解型的"], 4, "hard"),
    ("intermediate", ["中间的"], 5, "medium"),
    ("type", ["类型"], 8, "easy"),
    ("iia", ["IIA型"], 4, "hard"),
    ("iix", ["IIX型"], 4, "hard"),
    ("red", ["红的"], 6, "easy"),
    ("white", ["白的"], 6, "easy"),
    ("intermediate", ["中间型"], 5, "medium"),
    ("fatigue", ["疲劳"], 8, "medium"),
    ("resistant", ["抗疲劳的"], 5, "medium"),
    ("fibers", ["纤维"], 7, "easy"),
    ("endurance", ["耐力"], 8, "medium"),
    ("power", ["力量", "功率"], 9, "easy"),
    ("strength", ["力量"], 10, "easy"),
    ("velocity", ["速度"], 7, "medium"),
    ("tension", ["张力"], 7, "medium"),
    ("force", ["力"], 9, "easy"),
    ("torque", ["扭矩"], 6, "hard"),
    ("moment", ["力矩"], 6, "medium"),
    ("arm", ["力臂"], 6, "easy"),
    ("lever", ["杠杆"], 5, "medium"),
    ("fulcrum", ["支点"], 4, "medium"),
    ("effort", ["作用力"], 5, "medium"),
    ("resistance", ["阻力"], 8, "medium"),
    ("load", ["负荷"], 9, "easy"),
    ("stretch", ["拉伸"], 8, "easy"),
    ("shortening", ["缩短"], 6, "medium"),
    ("lengthening", ["延长"], 6, "medium"),
    ("elastic", ["弹性的"], 6, "medium"),
    ("component", ["成分"], 6, "easy"),
    ("parallel", ["平行的"], 5, "medium"),
    ("series", ["串联"], 5, "medium"),
    ("titin", ["肌联蛋白"], 4, "hard"),
    ("desmin", ["结蛋白"], 3, "hard"),
    ("vinculin", ["纽蛋白"], 3, "hard"),
    ("dystrophin", ["抗肌萎缩蛋白"], 3, "hard"),
    ("costamere", [" costamere", "肌膜附着点"], 3, "hard"),
    ("integrin", ["整合素"], 4, "hard"),
    ("titin", ["肌联蛋白"], 4, "hard"),
    ("myotilin", ["肌收蛋白"], 3, "hard"),
    ("telethonin", [" telethonin"], 3, "hard"),
    ("myopalladin", ["肌帕拉丁蛋白"], 3, "hard"),
]

# 领域3: 心血管与呼吸 (~120词)
cardio = [
    ("cardiovascular", ["心血管的"], 9, "hard"),
    ("heart", ["心脏"], 10, "easy"),
    ("cardiac", ["心脏的"], 8, "medium"),
    ("output", ["输出量"], 7, "medium"),
    ("stroke", ["每搏量"], 7, "medium"),
    ("volume", ["容积"], 8, "medium"),
    ("rate", ["心率"], 9, "easy"),
    ("chronotropic", ["变时性的"], 4, "hard"),
    ("inotropic", ["变力性的"], 4, "hard"),
    ("dromotropic", ["变传导性的"], 3, "hard"),
    ("contractility", ["收缩力"], 6, "hard"),
    ("preload", ["前负荷"], 6, "hard"),
    ("afterload", ["后负荷"], 6, "hard"),
    ("starling", ["斯塔林"], 4, "hard"),
    ("law", ["定律"], 6, "easy"),
    ("frank-starling", ["弗兰克-斯塔林机制"], 4, "hard"),
    ("mechanism", ["机制"], 7, "medium"),
    ("ejection", ["射血"], 6, "hard"),
    ("fraction", ["分数"], 6, "medium"),
    ("systole", ["收缩期"], 6, "hard"),
    ("diastole", ["舒张期"], 6, "hard"),
    ("atrium", ["心房"], 5, "hard"),
    ("ventricle", ["心室"], 5, "hard"),
    ("septum", ["间隔"], 4, "hard"),
    ("valve", ["瓣膜"], 5, "medium"),
    ("mitral", ["二尖瓣"], 4, "hard"),
    ("tricuspid", ["三尖瓣"], 4, "hard"),
    ("aortic", ["主动脉的"], 5, "hard"),
    ("pulmonary", ["肺动脉的"], 5, "hard"),
    ("semilunar", ["半月瓣"], 4, "hard"),
    ("myocardium", ["心肌"], 5, "hard"),
    ("endocardium", ["心内膜"], 4, "hard"),
    ("epicardium", ["心外膜"], 4, "hard"),
    ("pericardium", ["心包"], 4, "hard"),
    ("coronary", ["冠状动脉的"], 5, "hard"),
    ("artery", ["动脉"], 7, "medium"),
    ("vein", ["静脉"], 6, "medium"),
    ("capillary", ["毛细血管"], 6, "hard"),
    ("aorta", ["主动脉"], 5, "hard"),
    ("vena", ["静脉"], 4, "hard"),
    ("cava", ["腔静脉"], 4, "hard"),
    ("pulse", ["脉搏"], 6, "easy"),
    ("pressure", ["血压"], 9, "easy"),
    ("systolic", ["收缩压"], 6, "hard"),
    ("diastolic", ["舒张压"], 6, "hard"),
    ("mean", ["平均"], 7, "easy"),
    ("arterial", ["动脉的"], 5, "hard"),
    ("map", ["平均动脉压"], 5, "hard"),
    ("baroreceptor", ["压力感受器"], 5, "hard"),
    ("chemoreceptor", ["化学感受器"], 5, "hard"),
    ("reflex", ["反射"], 6, "medium"),
    ("bradycardia", ["心动过缓"], 5, "hard"),
    ("tachycardia", ["心动过速"], 5, "hard"),
    ("arrhythmia", ["心律失常"], 5, "hard"),
    ("fibrillation", ["颤动"], 4, "hard"),
    ("atrial", ["心房的"], 4, "hard"),
    ("flutter", ["扑动"], 4, "hard"),
    ("block", ["阻滞"], 5, "easy"),
    ("bundle", ["束"], 4, "medium"),
    ("branch", ["分支"], 5, "easy"),
    ("his", ["希氏束"], 4, "hard"),
    ("purkinje", ["浦肯野"], 4, "hard"),
    ("node", ["结"], 5, "medium"),
    ("sinus", ["窦房结"], 4, "hard"),
    ("AV", ["房室结"], 4, "hard"),
    ("electrocardiogram", ["心电图"], 6, "hard"),
    ("ecg", ["心电图"], 7, "hard"),
    ("ekg", ["心电图"], 6, "hard"),
    ("p-wave", ["P波"], 4, "hard"),
    ("qrs", ["QRS波群"], 4, "hard"),
    ("t-wave", ["T波"], 4, "hard"),
    ("segment", ["段"], 5, "medium"),
    ("interval", ["间期"], 6, "medium"),
    ("pr", ["PR间期"], 4, "hard"),
    ("qt", ["QT间期"], 4, "hard"),
    ("ST", ["ST段"], 4, "hard"),
    ("ischemia", ["缺血"], 5, "hard"),
    ("infarction", ["梗死"], 5, "hard"),
    ("angina", ["心绞痛"], 5, "hard"),
    ("pectoris", ["胸的"], 4, "hard"),
    ("hypertension", ["高血压"], 7, "hard"),
    ("hypotension", ["低血压"], 5, "hard"),
    ("atherosclerosis", ["动脉粥样硬化"], 5, "hard"),
    ("stenosis", ["狭窄"], 4, "hard"),
    ("regurgitation", ["反流"], 4, "hard"),
    ("insufficiency", ["功能不全"], 4, "hard"),
    ("failure", ["衰竭"], 6, "medium"),
    ("congestive", ["充血性"], 4, "hard"),
    ("CHF", ["充血性心力衰竭"], 4, "hard"),
    ("edema", ["水肿"], 5, "hard"),
    ("respiratory", ["呼吸的"], 7, "hard"),
    ("lung", ["肺"], 8, "easy"),
    ("pulmonary", ["肺的"], 6, "hard"),
    ("bronchus", ["支气管"], 5, "hard"),
    ("bronchiole", ["细支气管"], 4, "hard"),
    ("alveolus", ["肺泡"], 5, "hard"),
    ("pleura", ["胸膜"], 4, "hard"),
    ("diaphragm", ["膈肌"], 5, "hard"),
    ("intercostal", ["肋间的"], 4, "hard"),
    ("tidal", ["潮气的"], 5, "hard"),
    ("vital", ["肺活量"], 6, "medium"),
    ("capacity", ["容量"], 7, "medium"),
    ("forced", ["用力的"], 5, "medium"),
    ("expiratory", ["呼气的"], 5, "hard"),
    ("fev1", ["第一秒用力呼气容积"], 5, "hard"),
    ("fvc", ["用力肺活量"], 5, "hard"),
    ("residual", ["残气"], 4, "hard"),
    ("total", ["总量"], 6, "easy"),
    ("tlc", ["肺总量"], 4, "hard"),
    ("vc", ["肺活量"], 5, "hard"),
    ("ic", ["补吸气量"], 4, "hard"),
    ("erv", ["补呼气量"], 4, "hard"),
    ("ir", ["吸气储备量"], 4, "hard"),
    ("erv", ["呼气储备量"], 4, "hard"),
    ("compliance", ["顺应性"], 5, "hard"),
    ("elastance", ["弹性"], 4, "hard"),
    ("airway", ["气道"], 6, "medium"),
    ("resistance", ["阻力"], 7, "medium"),
    ("dead", ["死腔"], 5, "easy"),
    ("space", ["空间"], 6, "easy"),
    ("anatomical", ["解剖死腔"], 4, "hard"),
    ("alveolar", ["肺泡死腔"], 4, "hard"),
    ("ventilation-perfusion", ["通气/血流比"], 4, "hard"),
    ("ratio", ["比值"], 5, "medium"),
    ("shunt", ["分流"], 4, "hard"),
    ("diffusion", ["弥散"], 5, "medium"),
    ("capacity", ["能力"], 6, "medium"),
    ("DLCO", ["一氧化碳弥散量"], 4, "hard"),
    ("dyspnea", ["呼吸困难"], 5, "hard"),
    ("apnea", ["呼吸暂停"], 5, "hard"),
    ("hypopnea", ["低通气"], 4, "hard"),
    ("hyperpnea", ["过度通气"], 4, "hard"),
    ("tachypnea", ["呼吸急促"], 4, "hard"),
    ("bradypnea", ["呼吸过缓"], 3, "hard"),
    ("kussmaul", ["库斯莫尔呼吸"], 3, "hard"),
    ("cheyne-stokes", ["陈-施呼吸"], 3, "hard"),
]

# 领域4: 运动处方与测试 (~130词)
prescription = [
    ("prescription", ["处方"], 9, "hard"),
    ("exercise", ["运动"], 10, "easy"),
    ("training", ["训练"], 10, "easy"),
    ("program", ["方案", "计划"], 9, "easy"),
    ("protocol", ["方案"], 7, "medium"),
    ("guideline", ["指南"], 7, "medium"),
    ("recommendation", ["建议"], 7, "medium"),
    ("intensity", ["强度"], 9, "medium"),
    ("duration", ["持续时间"], 8, "medium"),
    ("frequency", ["频率"], 8, "medium"),
    ("volume", ["量"], 8, "medium"),
    ("load", ["负荷"], 9, "easy"),
    ("progression", ["进阶"], 7, "hard"),
    ("periodization", ["周期化"], 6, "hard"),
    ("macrocycle", ["大周期"], 5, "hard"),
    ("mesocycle", ["中周期"], 5, "hard"),
    ("microcycle", ["小周期"], 5, "hard"),
    ("block", ["板块"], 5, "easy"),
    ("linear", ["线性的"], 6, "medium"),
    ("undulating", ["波动的"], 5, "hard"),
    ("daily", ["日波动"], 4, "hard"),
    ("undulating", ["波动的"], 5, "hard"),
    ("non-linear", ["非线性的"], 5, "hard"),
    ("reverse", ["反向的"], 5, "medium"),
    ("stepwise", ["阶梯式"], 4, "hard"),
    ("FITT", ["FITT原则"], 7, "hard"),
    ("FITT-VP", ["FITT-VP原则"], 6, "hard"),
    ("overload", ["超负荷"], 8, "hard"),
    ("progressive", ["渐进性"], 7, "hard"),
    ("specificity", ["专门性"], 7, "hard"),
    ("reversibility", ["可逆性"], 6, "hard"),
    ("individuality", ["个体化"], 6, "hard"),
    ("diminishing", ["递减的"], 5, "hard"),
    ("returns", ["收益"], 5, "medium"),
    ("recovery", ["恢复"], 8, "medium"),
    ("adaptation", ["适应"], 8, "hard"),
    ("detraining", ["停训"], 6, "hard"),
    ("maintenance", ["维持"], 6, "medium"),
    ("warm-up", ["热身"], 8, "medium"),
    ("cool-down", ["整理活动"], 7, "medium"),
    ("stretching", ["拉伸"], 8, "medium"),
    ("flexibility", ["柔韧性"], 8, "hard"),
    ("ROM", ["关节活动度"], 7, "hard"),
    ("range", ["范围"], 7, "easy"),
    ("motion", ["运动"], 7, "easy"),
    ("static", ["静态的"], 7, "medium"),
    ("dynamic", ["动态的"], 7, "medium"),
    ("ballistic", ["弹震式的"], 5, "hard"),
    ("proprioceptive", ["本体感觉的"], 5, "hard"),
    ("neuromuscular", ["神经肌肉的"], 5, "hard"),
    ("facilitation", ["促进"], 5, "hard"),
    ("PNF", ["本体感觉神经肌肉促进法"], 6, "hard"),
    ("agonist", ["主动肌"], 6, "hard"),
    ("contract-relax", ["收缩-放松"], 5, "hard"),
    ("hold-relax", ["保持-放松"], 5, "hard"),
    ("repetition", ["重复次数"], 8, "hard"),
    ("repetition maximum", ["最大重复次数"], 7, "hard"),
    ("RM", ["最大重复次数"], 8, "hard"),
    ("1RM", ["一次最大重量"], 8, "hard"),
    ("set", ["组"], 9, "easy"),
    ("rest", ["休息"], 9, "easy"),
    ("interval", ["间歇"], 8, "medium"),
    ("work", ["工作"], 8, "easy"),
    ("recovery", ["恢复"], 8, "medium"),
    ("ratio", ["比值"], 6, "medium"),
    ("tempo", ["节奏"], 6, "medium"),
    ("time", ["时间"], 8, "easy"),
    ("under", ["在...之下"], 7, "easy"),
    ("tension", ["张力"], 7, "medium"),
    ("TUT", ["张力下时间"], 6, "hard"),
    ("eccentric", ["离心"], 7, "hard"),
    ("concentric", ["向心"], 7, "hard"),
    ("isometric", ["等长"], 7, "hard"),
    ("accentuated", ["增强的"], 4, "hard"),
    ("eccentric", ["离心"], 6, "hard"),
    (" overload", ["超负荷"], 5, "hard"),
    ("blood", ["血液"], 8, "easy"),
    ("flow", [" flow", "流动"], 7, "easy"),
    ("restriction", ["限制"], 6, "medium"),
    ("BFR", ["血流限制训练"], 6, "hard"),
    ("kaatsu", ["加压训练"], 4, "hard"),
    ("occlusion", ["闭塞"], 5, "hard"),
    ("vascular", ["血管的"], 5, "hard"),
    ("metabolic", ["代谢的"], 6, "hard"),
    ("stress", ["应激"], 7, "easy"),
    ("hypoxia", ["缺氧"], 5, "hard"),
    ("cluster", ["集群"], 5, "medium"),
    ("set", ["组"], 6, "easy"),
    ("rest-pause", ["休息-暂停"], 5, "hard"),
    ("drop", ["递减"], 5, "easy"),
    ("pyramid", ["金字塔"], 5, "medium"),
    ("reverse", ["反向"], 5, "medium"),
    ("giant", ["巨型"], 4, "medium"),
    ("superset", ["超级组"], 5, "hard"),
    ("tri-set", ["三合组"], 4, "hard"),
    ("circuit", ["循环"], 6, "medium"),
    ("HIT", ["高强度训练"], 7, "hard"),
    ("HIIT", ["高强度间歇训练"], 8, "hard"),
    ("SIT", ["冲刺间歇训练"], 6, "hard"),
    ("MICT", ["中等强度持续训练"], 5, "hard"),
    ("Tabata", ["塔巴塔训练"], 5, "hard"),
    ("EMOM", ["每分钟完成"], 5, "hard"),
    ("AMRAP", ["尽可能多做"], 5, "hard"),
    ("RPE", ["主观疲劳程度"], 8, "hard"),
    ("Borg", ["博格量表"], 6, "hard"),
    ("scale", ["量表"], 6, "medium"),
    ("OMNI", ["OMNI量表"], 5, "hard"),
    ("talk", ["谈话"], 5, "easy"),
    ("test", [" test", "测试"], 6, "easy"),
    ("heart rate reserve", ["心率储备"], 6, "hard"),
    ("HRR", ["心率储备"], 6, "hard"),
    ("Karvonen", ["卡沃宁公式"], 4, "hard"),
    ("formula", ["公式"], 6, "medium"),
    ("target", ["目标"], 7, "easy"),
    ("zone", ["区间"], 7, "easy"),
    ("MET", ["代谢当量"], 8, "hard"),
    ("metabolic", ["代谢的"], 6, "hard"),
    ("equivalent", ["当量"], 6, "hard"),
    ("task", [" task", "任务"], 6, "easy"),
    ("walk", ["步行"], 7, "easy"),
    ("test", [" test"], 6, "easy"),
    ("rockport", ["罗克波特"], 4, "hard"),
    ("queens", ["皇后"], 4, "hard"),
    ("college", ["学院"], 5, "easy"),
    ("step", ["台阶"], 6, "easy"),
    ("bruce", ["布鲁斯"], 4, "hard"),
    ("balke", ["巴尔克"], 4, "hard"),
    ("graded", ["分级"], 5, "medium"),
    ("treadmill", ["跑步机"], 6, "medium"),
    ("cycle", ["自行车"], 6, "easy"),
    ("ergometer", ["测功计"], 5, "hard"),
    ("arm", ["臂"], 6, "easy"),
    ("leg", ["腿"], 6, "easy"),
    ("Wingate", ["温盖特测试"], 5, "hard"),
    ("anaerobic", ["无氧"], 6, "medium"),
    ("power", ["功率"], 7, "easy"),
    ("test", [" test"], 6, "easy"),
    ("vertical", ["垂直"], 5, "medium"),
    ("jump", ["跳跃"], 6, "easy"),
    ("sit-and-reach", ["坐位体前屈"], 5, "hard"),
    ("push-up", ["俯卧撑"], 6, "medium"),
    ("sit-up", ["仰卧起坐"], 5, "medium"),
    ("curl-up", ["卷腹"], 4, "hard"),
    ("grip", ["握力"], 5, "medium"),
    ("strength", ["力量"], 8, "easy"),
    ("test", ["测试"], 7, "easy"),
    ("isokinetic", ["等速"], 6, "hard"),
    ("dynamometer", ["测力计"], 5, "hard"),
    ("handheld", ["手持式"], 4, "medium"),
    ("dynamometer", ["测力计"], 5, "hard"),
    ("back", ["背"], 6, "easy"),
    ("scratch", ["抓"], 4, "easy"),
    ("test", [" test"], 5, "easy"),
    ("shoulder", ["肩"], 6, "medium"),
    ("abduction", ["外展"], 5, "hard"),
    ("ACSM", ["美国运动医学学会"], 9, "hard"),
]

# 领域5: 体适能与训练方法 (~130词)
fitness = [
    ("fitness", ["体适能", " fitness"], 9, "easy"),
    ("physical", ["身体的"], 8, "medium"),
    ("activity", ["活动"], 9, "easy"),
    ("health", ["健康"], 9, "easy"),
    ("related", ["相关的"], 7, "easy"),
    ("skill", ["技能"], 7, "easy"),
    ("components", ["成分"], 6, "easy"),
    ("cardiorespiratory", ["心肺耐力"], 7, "hard"),
    ("endurance", ["耐力"], 8, "medium"),
    ("muscular", ["肌肉的"], 8, "medium"),
    ("strength", ["力量"], 9, "easy"),
    ("endurance", ["耐力"], 8, "medium"),
    ("power", ["爆发力"], 8, "easy"),
    ("flexibility", ["柔韧性"], 8, "hard"),
    ("body", ["身体"], 9, "easy"),
    ("composition", ["成分"], 7, "medium"),
    ("agility", ["敏捷性"], 6, "hard"),
    ("balance", ["平衡"], 7, "medium"),
    ("coordination", ["协调性"], 6, "hard"),
    ("speed", ["速度"], 7, "easy"),
    ("reaction", ["反应"], 6, "medium"),
    ("time", ["时间"], 7, "easy"),
    ("aerobic", ["有氧"], 8, "medium"),
    ("capacity", ["能力"], 7, "medium"),
    ("anaerobic", ["无氧"], 7, "medium"),
    ("lactate", ["乳酸"], 6, "medium"),
    ("threshold", ["阈值"], 6, "medium"),
    ("critical", ["临界"], 5, "medium"),
    ("power", ["功率"], 6, "easy"),
    ("FTP", ["功能性阈值功率"], 5, "hard"),
    ("functional", ["功能性的"], 6, "hard"),
    ("threshold", ["阈值"], 5, "medium"),
    ("Wingate", ["温盖特"], 4, "hard"),
    ("anaerobic", ["无氧"], 5, "medium"),
    ("capacity", ["能力"], 5, "medium"),
    ("WAC", ["无氧工作能力"], 4, "hard"),
    ("aerobic", ["有氧"], 6, "medium"),
    ("capacity", ["能力"], 5, "medium"),
    ("walking", ["步行"], 7, "easy"),
    ("running", ["跑步"], 7, "easy"),
    ("jogging", ["慢跑"], 6, "easy"),
    ("cycling", ["骑行"], 6, "easy"),
    ("swimming", ["游泳"], 6, "easy"),
    ("rowing", ["划船"], 5, "easy"),
    ("cross-country", ["越野"], 5, "hard"),
    ("skiing", ["滑雪"], 5, "easy"),
    ("elliptical", ["椭圆机"], 5, "hard"),
    ("stair", ["楼梯"], 5, "easy"),
    ("climbing", ["攀爬"], 5, "easy"),
    ("dancing", ["舞蹈"], 5, "easy"),
    ("aerobics", ["有氧运动"], 5, "hard"),
    ("spinning", ["动感单车"], 5, "hard"),
    ("kickboxing", ["搏击操"], 5, "hard"),
    ("pilates", ["普拉提"], 6, "hard"),
    ("yoga", ["瑜伽"], 6, "easy"),
    ("tai", ["太极"], 5, "easy"),
    ("chi", ["气"], 5, "easy"),
    ("calisthenics", ["徒手体操"], 4, "hard"),
    ("bodyweight", ["体重"], 5, "medium"),
    ("training", ["训练"], 8, "easy"),
    ("free", ["自由"], 6, "easy"),
    ("weight", ["重量"], 7, "easy"),
    ("machine", ["器械"], 6, "medium"),
    ("cable", ["绳索"], 5, "medium"),
    ("pulley", ["滑轮"], 4, "hard"),
    ("smith", ["史密斯"], 4, "hard"),
    ("machine", ["机器"], 5, "easy"),
    ("kettlebell", ["壶铃"], 5, "hard"),
    ("dumbbell", ["哑铃"], 6, "medium"),
    ("barbell", ["杠铃"], 6, "medium"),
    ("plate", ["配重片"], 5, "easy"),
    ("collar", ["卡箍"], 4, "medium"),
    ("bench", ["长凳"], 5, "easy"),
    ("rack", ["架"], 5, "easy"),
    ("cage", ["笼"], 4, "easy"),
    ("power", ["力量"], 6, "easy"),
    ("squat", ["深蹲"], 7, "medium"),
    ("deadlift", ["硬拉"], 6, "medium"),
    ("bench", ["卧推"], 6, "easy"),
    ("press", [" press", "推举"], 6, "easy"),
    ("overhead", ["过头"], 5, "medium"),
    ("pull-up", ["引体向上"], 6, "medium"),
    ("chin-up", ["反握引体向上"], 5, "hard"),
    ("dip", ["双杠臂屈伸"], 5, "medium"),
    ("push-up", ["俯卧撑"], 6, "medium"),
    ("lunge", ["弓步"], 5, "medium"),
    ("step-up", ["上台阶"], 5, "medium"),
    ("leg", ["腿"], 6, "easy"),
    ("press", [" press"], 5, "easy"),
    ("curl", ["弯举"], 5, "medium"),
    ("extension", ["伸展"], 6, "medium"),
    ("fly", ["飞鸟"], 4, "medium"),
    ("row", ["划船"], 5, "easy"),
    ("face", ["面拉"], 4, "easy"),
    ("pull", [" pull", "拉"], 5, "easy"),
    ("shrug", ["耸肩"], 4, "medium"),
    ("raise", ["侧平举"], 5, "medium"),
    ("lateral", ["侧向的"], 4, "medium"),
    ("crunch", ["卷腹"], 5, "medium"),
    ("plank", ["平板支撑"], 6, "medium"),
    ("bridge", ["臀桥"], 5, "medium"),
    ("hyperextension", ["背伸"], 4, "hard"),
    ("back", ["背"], 5, "easy"),
    ("extension", [" extension"], 5, "medium"),
    ("russian", ["俄式"], 4, "medium"),
    ("twist", ["转体"], 4, "easy"),
    ("woodchop", ["伐木"], 4, "hard"),
    ("farmer", ["农夫"], 4, "easy"),
    ("walk", ["行走"], 5, "easy"),
    ("turkish", ["土耳其"], 4, "medium"),
    ("get-up", ["起立"], 4, "medium"),
    ("swing", ["摇摆"], 5, "easy"),
    ("snatch", ["抓举"], 5, "hard"),
    ("clean", ["高翻"], 5, "hard"),
    ("jerk", ["挺举"], 5, "hard"),
    ("power", ["高抓"], 5, "easy"),
    ("hang", ["悬垂"], 4, "easy"),
    ("muscle-up", ["双力臂"], 4, "hard"),
    ("handstand", ["倒立"], 5, "hard"),
    ("push-up", ["俯卧撑"], 5, "medium"),
    ("pistol", ["手枪深蹲"], 4, "hard"),
    ("squat", ["深蹲"], 5, "medium"),
    ("nordic", ["北欧挺"], 4, "hard"),
    ("curl", ["弯举"], 4, "medium"),
    ("glute-ham", ["臀腿"], 4, "hard"),
    ("raise", [" raise"], 4, "medium"),
    ("calf", ["小腿"], 5, "medium"),
    ("tibialis", ["胫骨前肌"], 4, "hard"),
    ("anterior", ["前侧"], 4, "medium"),
    ("raise", [" raise"], 4, "medium"),
    ("sled", ["雪橇"], 4, "medium"),
    ("push", ["推"], 5, "easy"),
    ("pull", ["拉"], 5, "easy"),
    ("drag", ["拖"], 4, "easy"),
    ("prowler", ["推车"], 4, "hard"),
    ("battle", ["战绳"], 4, "medium"),
    ("rope", ["绳索"], 5, "easy"),
    ("sled", ["雪橇"], 4, "medium"),
    ("hammer", ["锤"], 4, "easy"),
    ("tyre", ["轮胎"], 4, "easy"),
    ("flip", ["翻转"], 4, "easy"),
    ("sandbag", ["沙袋"], 4, "hard"),
    ("medicine", ["药球"], 5, "medium"),
    ("ball", ["球"], 5, "easy"),
    ("slam", ["砸球"], 4, "medium"),
    ("throw", ["投掷"], 5, "easy"),
    ("bosu", ["波速球"], 4, "hard"),
    ("balance", ["平衡"], 5, "medium"),
    ("trainer", ["训练器"], 5, "medium"),
    ("stability", ["稳定"], 6, "hard"),
    ("ball", ["球"], 5, "easy"),
    ("foam", ["泡沫"], 5, "easy"),
    ("roller", ["轴"], 5, "easy"),
    ("massage", ["按摩"], 6, "easy"),
    ("stick", ["棍"], 4, "easy"),
    ("lacrosse", [" lacrosse"], 4, "hard"),
    ("ball", ["球"], 4, "easy"),
    ("theragun", ["筋膜枪"], 4, "hard"),
    ("percussion", [" percussion", "敲击"], 4, "hard"),
    ("massager", ["按摩器"], 4, "medium"),
    ("compression", ["加压"], 5, "hard"),
    ("boots", ["靴"], 4, "easy"),
    ("normatec", [" normatec"], 3, "hard"),
    ("cryotherapy", ["冷冻疗法"], 4, "hard"),
    ("contrast", ["对比"], 4, "medium"),
    ("bath", ["浴"], 4, "easy"),
    ("sauna", ["桑拿"], 5, "easy"),
    ("infrared", ["红外"], 4, "hard"),
    ("float", ["漂浮"], 4, "easy"),
    ("tank", [" tank", "舱"], 4, "easy"),
    ("sensory", ["感觉的"], 4, "hard"),
    ("deprivation", ["剥夺"], 4, "hard"),
]

# 领域6: 代谢与营养 (~100词)
nutrition = [
    ("nutrition", ["营养"], 8, "medium"),
    ("diet", ["饮食"], 8, "easy"),
    ("macronutrient", ["常量营养素"], 6, "hard"),
    ("micronutrient", ["微量营养素"], 6, "hard"),
    ("carbohydrate", ["碳水化合物"], 8, "hard"),
    ("protein", ["蛋白质"], 9, "easy"),
    ("fat", ["脂肪"], 8, "easy"),
    ("fiber", ["膳食纤维"], 7, "easy"),
    ("water", ["水"], 8, "easy"),
    ("vitamin", ["维生素"], 8, "medium"),
    ("mineral", ["矿物质"], 7, "medium"),
    ("antioxidant", ["抗氧化剂"], 6, "hard"),
    ("electrolyte", ["电解质"], 6, "hard"),
    ("sodium", ["钠"], 6, "medium"),
    ("potassium", ["钾"], 6, "medium"),
    ("calcium", ["钙"], 6, "medium"),
    ("magnesium", ["镁"], 5, "hard"),
    ("phosphorus", ["磷"], 5, "hard"),
    ("iron", ["铁"], 6, "easy"),
    ("zinc", ["锌"], 5, "easy"),
    ("selenium", ["硒"], 4, "hard"),
    ("iodine", ["碘"], 5, "hard"),
    ("chromium", ["铬"], 4, "hard"),
    ("copper", ["铜"], 4, "easy"),
    ("manganese", ["锰"], 4, "hard"),
    ("molybdenum", ["钼"], 3, "hard"),
    ("fluoride", ["氟"], 4, "hard"),
    ("boron", ["硼"], 3, "hard"),
    ("vanadium", ["钒"], 3, "hard"),
    ("nickel", ["镍"], 3, "hard"),
    ("silicon", ["硅"], 4, "hard"),
    ("tin", ["锡"], 3, "easy"),
    ("cobalt", ["钴"], 4, "hard"),
    ("vitamin A", ["维生素A"], 5, "hard"),
    ("vitamin C", ["维生素C"], 6, "hard"),
    ("vitamin D", ["维生素D"], 6, "hard"),
    ("vitamin E", ["维生素E"], 5, "hard"),
    ("vitamin K", ["维生素K"], 5, "hard"),
    ("thiamine", ["硫胺素"], 4, "hard"),
    ("riboflavin", ["核黄素"], 4, "hard"),
    ("niacin", ["烟酸"], 5, "hard"),
    ("pantothenic", ["泛酸"], 4, "hard"),
    ("pyridoxine", ["吡哆醇"], 4, "hard"),
    ("biotin", ["生物素"], 4, "hard"),
    ("folate", ["叶酸"], 5, "hard"),
    ("cobalamin", ["钴胺素"], 4, "hard"),
    ("calorie", ["卡路里"], 8, "easy"),
    ("kilocalorie", ["千卡"], 6, "hard"),
    ("joule", ["焦耳"], 5, "hard"),
    ("basal", ["基础的"], 6, "medium"),
    ("BMR", ["基础代谢率"], 7, "hard"),
    ("resting", ["静息的"], 6, "medium"),
    ("RMR", ["静息代谢率"], 6, "hard"),
    ("TDEE", ["每日总能量消耗"], 6, "hard"),
    ("thermic", ["食物热效应"], 5, "hard"),
    ("effect", ["效应"], 6, "easy"),
    ("TEF", ["食物热效应"], 5, "hard"),
    ("NEAT", ["非运动性活动产热"], 5, "hard"),
    ("EPOC", ["运动后过量氧耗"], 5, "hard"),
    ("glycemic", ["血糖的"], 5, "hard"),
    ("index", ["指数"], 6, "easy"),
    ("GI", ["血糖生成指数"], 7, "hard"),
    ("load", ["负荷"], 6, "easy"),
    ("GL", ["血糖负荷"], 6, "hard"),
    ("insulin", ["胰岛素"], 7, "medium"),
    ("sensitivity", ["敏感性"], 6, "hard"),
    ("resistance", ["抵抗"], 6, "medium"),
    ("ketosis", ["酮症"], 5, "hard"),
    ("ketone", ["酮体"], 5, "hard"),
    ("gluconeogenesis", ["糖异生"], 4, "hard"),
    ("lipolysis", ["脂肪分解"], 5, "hard"),
    ("beta-oxidation", ["β氧化"], 4, "hard"),
    ("de novo", ["从头合成"], 4, "hard"),
    ("lipogenesis", ["脂肪生成"], 4, "hard"),
    ("proteolysis", ["蛋白质分解"], 4, "hard"),
    ("nitrogen", ["氮"], 5, "medium"),
    ("balance", ["平衡"], 6, "easy"),
    ("positive", ["正氮"], 5, "medium"),
    ("negative", ["负氮"], 5, "medium"),
    ("hydration", ["水合状态"], 6, "hard"),
    ("dehydration", ["脱水"], 6, "hard"),
    ("euhydration", ["正常水合"], 5, "hard"),
    ("hyperhydration", ["过水合"], 4, "hard"),
    ("hypohydration", ["低水合"], 4, "hard"),
    ("osmolality", ["渗透压"], 4, "hard"),
    ("specific", ["比重"], 5, "medium"),
    ("gravity", ["重力"], 5, "easy"),
    ("urine", ["尿液"], 5, "medium"),
    ("color", ["颜色"], 5, "easy"),
    ("chart", ["图表"], 5, "easy"),
    ("sweat", ["汗液"], 6, "easy"),
    ("rate", [" rate", "速率"], 5, "easy"),
    ("sodium", ["钠"], 5, "medium"),
    ("loss", ["损失"], 5, "easy"),
    ("cramp", ["痉挛"], 5, "easy"),
    ("heat", ["热"], 6, "easy"),
    ("illness", ["疾病"], 5, "medium"),
    ("stroke", ["中暑"], 5, "medium"),
    ("exertional", ["运动性"], 5, "hard"),
    ("hyponatremia", ["低钠血症"], 4, "hard"),
    ("cramp", ["痉挛"], 5, "easy"),
]

# 领域7: 损伤预防与康复 (~100词)
rehab = [
    ("rehabilitation", ["康复"], 8, "hard"),
    ("prevention", ["预防"], 8, "medium"),
    ("injury", ["损伤"], 9, "easy"),
    ("risk", ["风险"], 8, "easy"),
    ("factor", ["因素"], 8, "easy"),
    ("mechanism", ["机制"], 7, "medium"),
    ("acute", ["急性的"], 7, "medium"),
    ("chronic", ["慢性的"], 7, "medium"),
    ("overuse", ["过度使用"], 7, "hard"),
    ("trauma", ["创伤"], 6, "hard"),
    ("fracture", ["骨折"], 6, "hard"),
    ("dislocation", ["脱位"], 5, "hard"),
    ("subluxation", ["半脱位"], 4, "hard"),
    ("sprain", ["扭伤"], 6, "medium"),
    ("strain", ["拉伤"], 6, "medium"),
    ("contusion", ["挫伤"], 5, "hard"),
    ("abrasion", ["擦伤"], 4, "hard"),
    ("laceration", ["裂伤"], 4, "hard"),
    ("puncture", ["刺伤"], 4, "hard"),
    ("avulsion", ["撕脱"], 4, "hard"),
    ("hematoma", ["血肿"], 4, "hard"),
    ("edema", ["水肿"], 5, "hard"),
    ("effusion", ["积液"], 4, "hard"),
    ("inflammation", ["炎症"], 7, "hard"),
    ("swelling", ["肿胀"], 6, "easy"),
    ("pain", ["疼痛"], 9, "easy"),
    ("tenderness", ["压痛"], 5, "hard"),
    ("spasm", ["痉挛"], 5, "medium"),
    ("guarding", ["保护性肌紧张"], 4, "hard"),
    ("instability", ["不稳"], 5, "hard"),
    ("impingement", ["撞击"], 5, "hard"),
    ("syndrome", ["综合征"], 6, "medium"),
    ("tendinopathy", ["肌腱病"], 5, "hard"),
    ("tendinosis", ["肌腱变性"], 4, "hard"),
    ("bursitis", ["滑囊炎"], 4, "hard"),
    ("capsulitis", ["囊炎"], 4, "hard"),
    ("synovitis", ["滑膜炎"], 4, "hard"),
    ("chondromalacia", ["软骨软化"], 4, "hard"),
    ("patella", ["髌骨"], 5, "hard"),
    ("meniscus", ["半月板"], 5, "hard"),
    ("cruciate", ["交叉的"], 4, "hard"),
    ("ligament", ["韧带"], 6, "hard"),
    ("ACL", ["前交叉韧带"], 7, "hard"),
    ("PCL", ["后交叉韧带"], 6, "hard"),
    ("MCL", ["内侧副韧带"], 6, "hard"),
    ("LCL", ["外侧副韧带"], 6, "hard"),
    ("rotator", ["肩袖"], 5, "hard"),
    ("cuff", ["袖"], 5, "easy"),
    ("supraspinatus", ["冈上肌"], 4, "hard"),
    ("infraspinatus", ["冈下肌"], 4, "hard"),
    ("teres", ["小圆肌"], 4, "hard"),
    ("minor", ["小的"], 5, "easy"),
    ("subscapularis", ["肩胛下肌"], 4, "hard"),
    ("SLAP", ["上盂唇前后撕裂"], 5, "hard"),
    ("lesion", ["损伤"], 5, "medium"),
    ("labrum", ["盂唇"], 4, "hard"),
    ("glenoid", ["关节盂"], 4, "hard"),
    ("Bankart", ["班卡特"], 4, "hard"),
    ("Hill-Sachs", ["希尔-萨克斯"], 4, "hard"),
    ("dislocation", ["脱位"], 5, "hard"),
    ("shoulder", ["肩关节"], 6, "medium"),
    ("epicondylitis", ["上髁炎"], 5, "hard"),
    ("lateral", ["外侧"], 5, "medium"),
    ("medial", ["内侧"], 5, "medium"),
    ("golfer", ["高尔夫球肘"], 4, "medium"),
    ("tennis", ["网球肘"], 5, "easy"),
    ("elbow", ["肘"], 6, "easy"),
    ("carpal", ["腕管"], 4, "hard"),
    ("tunnel", ["隧道"], 4, "easy"),
    ("syndrome", ["综合征"], 5, "medium"),
    ("de", [" de"], 4, "easy"),
    ("Quervain", ["奎尔万"], 4, "hard"),
    ("tendinitis", ["肌腱炎"], 4, "hard"),
    ("snapping", ["弹响"], 4, "medium"),
    ("hip", ["髋"], 6, "easy"),
    ("groin", ["腹股沟"], 5, "medium"),
    ("pull", ["拉伤"], 5, "easy"),
    ("hamstring", ["腘绳肌"], 6, "hard"),
    ("quadriceps", ["股四头肌"], 6, "hard"),
    ("strain", ["拉伤"], 5, "medium"),
    ("contusion", ["挫伤"], 5, "hard"),
    ("cruciate", ["交叉"], 4, "hard"),
    ("ligament", ["韧带"], 5, "hard"),
    ("meniscus", ["半月板"], 5, "hard"),
    ("tear", ["撕裂"], 5, "easy"),
    ("patellofemoral", ["髌股"], 4, "hard"),
    ("pain", ["疼痛"], 5, "easy"),
    ("syndrome", ["综合征"], 4, "medium"),
    ("PFPS", ["髌股疼痛综合征"], 5, "hard"),
    ("patellar", ["髌骨的"], 4, "hard"),
    ("tendinitis", ["肌腱炎"], 4, "hard"),
    ("jumper", ["跳跃者膝"], 4, "medium"),
    ("knee", ["膝"], 6, "easy"),
    ("Osgood-Schlatter", ["奥斯古德-施拉特"], 3, "hard"),
    ("iliotibial", ["髂胫束"], 4, "hard"),
    ("band", ["束带"], 4, "easy"),
    ("friction", ["摩擦"], 5, "medium"),
    ("syndrome", ["综合征"], 4, "medium"),
    ("ITBS", ["髂胫束摩擦综合征"], 4, "hard"),
    ("shin", ["胫骨"], 5, "easy"),
    ("splints", ["夹板"], 4, "medium"),
    ("stress", ["应力"], 5, "easy"),
    ("fracture", ["骨折"], 4, "hard"),
    ("Achilles", ["跟腱"], 5, "hard"),
    ("tendinitis", ["肌腱炎"], 4, "hard"),
    ("rupture", ["断裂"], 4, "medium"),
    ("ankle", ["踝"], 6, "easy"),
    ("sprain", ["扭伤"], 5, "medium"),
    ("inversion", ["内翻"], 4, "hard"),
    ("eversion", ["外翻"], 4, "hard"),
    ("high", ["高位"], 4, "easy"),
    ("ankle", ["踝"], 5, "easy"),
    ("plantar", ["足底"], 5, "hard"),
    ("fasciitis", ["筋膜炎"], 4, "hard"),
    ("heel", ["足跟"], 5, "easy"),
    ("spur", ["骨刺"], 4, "medium"),
    ("Morton", ["莫顿"], 4, "hard"),
    ("neuroma", ["神经瘤"], 4, "hard"),
    ("sesamoiditis", ["籽骨炎"], 3, "hard"),
    ("turf", ["人工草皮"], 4, "easy"),
    ("toe", ["趾"], 4, "easy"),
    ("Jones", ["琼斯"], 4, "hard"),
    ("fracture", ["骨折"], 4, "hard"),
    ("Lisfranc", ["利斯弗朗"], 3, "hard"),
    ("injury", ["损伤"], 4, "easy"),
    ("concussion", ["脑震荡"], 5, "hard"),
    ("TBI", ["创伤性脑损伤"], 5, "hard"),
    ("whiplash", ["挥鞭伤"], 4, "hard"),
    ("herniated", ["突出"], 4, "hard"),
    ("disc", ["椎间盘"], 5, "medium"),
    ("sciatica", ["坐骨神经痛"], 4, "hard"),
    ("spondylolysis", ["椎弓峡部裂"], 3, "hard"),
    ("spondylolisthesis", ["脊椎滑脱"], 3, "hard"),
    ("scoliosis", ["脊柱侧弯"], 4, "hard"),
    ("kyphosis", ["驼背"], 4, "hard"),
    ("lordosis", ["腰椎前凸"], 4, "hard"),
    ("RSI", ["重复性劳损"], 5, "hard"),
    ("overtraining", ["过度训练"], 6, "hard"),
    ("syndrome", ["综合征"], 5, "medium"),
    ("OTS", ["过度训练综合征"], 5, "hard"),
    ("underrecovery", ["恢复不足"], 4, "hard"),
    ("staleness", [" stale"], 4, "hard"),
]

# 领域9: 额外补充 (~100词，凑到1000)
extra = [
    ("adenosine", ["腺苷"], 4, "hard"),
    ("phosphate", ["磷酸"], 5, "hard"),
    ("creatine", ["肌酸"], 6, "hard"),
    ("supplement", ["补剂"], 6, "medium"),
    ("whey", ["乳清"], 5, "hard"),
    ("casein", ["酪蛋白"], 4, "hard"),
    ("BCAA", ["支链氨基酸"], 6, "hard"),
    ("leucine", ["亮氨酸"], 5, "hard"),
    ("isoleucine", ["异亮氨酸"], 4, "hard"),
    ("valine", ["缬氨酸"], 4, "hard"),
    ("glutamine", ["谷氨酰胺"], 5, "hard"),
    ("arginine", ["精氨酸"], 4, "hard"),
    ("citrulline", ["瓜氨酸"], 4, "hard"),
    ("beta-alanine", ["β-丙氨酸"], 5, "hard"),
    ("caffeine", ["咖啡因"], 6, "hard"),
    ("nitrate", ["硝酸盐"], 5, "hard"),
    ("beetroot", ["甜菜根"], 4, "hard"),
    ("juice", ["汁"], 4, "easy"),
    ("HMB", ["β-羟基-β-甲基丁酸"], 4, "hard"),
    ("omega-3", ["欧米伽3"], 5, "hard"),
    ("fatty acid", ["脂肪酸"], 5, "hard"),
    ("DHA", ["二十二碳六烯酸"], 4, "hard"),
    ("EPA", ["二十碳五烯酸"], 4, "hard"),
    ("collagen", ["胶原蛋白"], 5, "hard"),
    ("peptide", ["肽"], 5, "hard"),
    ("hydrolysate", ["水解物"], 4, "hard"),
    ("isolate", ["分离物"], 4, "hard"),
    ("concentrate", ["浓缩物"], 4, "hard"),
    ("denatured", ["变性的"], 4, "hard"),
    ("undenatured", ["未变性的"], 3, "hard"),
    ("micellar", ["胶束的"], 3, "hard"),
    ("spike", ["峰值"], 5, "easy"),
    ("insulin", ["胰岛素"], 5, "medium"),
    ("anabolic", ["合成的"], 5, "hard"),
    ("window", ["窗口"], 5, "easy"),
    ("nutrient", ["营养素"], 6, "medium"),
    ("timing", ["时机"], 6, "medium"),
    ("pre-workout", ["运动前"], 5, "hard"),
    ("post-workout", ["运动后"], 5, "hard"),
    ("intra-workout", ["运动中"], 4, "hard"),
    ("meal", ["餐"], 6, "easy"),
    ("replacement", ["替代"], 4, "medium"),
    ("bar", ["棒"], 5, "easy"),
    ("gel", ["胶"], 4, "easy"),
    ("electrolyte", ["电解质"], 5, "hard"),
    ("drink", ["饮料"], 5, "easy"),
    ("sports", ["运动"], 6, "easy"),
    ("drink", ["饮料"], 5, "easy"),
    ("hypertonic", ["高渗"], 4, "hard"),
    ("hypotonic", ["低渗"], 4, "hard"),
    ("isotonic", ["等渗"], 4, "hard"),
    ("palatability", ["适口性"], 3, "hard"),
    ("osmolality", ["渗透压"], 4, "hard"),
    ("gastric", ["胃的"], 4, "hard"),
    ("emptying", ["排空"], 4, "medium"),
    ("rehydration", ["补液"], 5, "hard"),
    ("prehydration", ["预水合"], 4, "hard"),
    ("hypohydration", ["低水合"], 4, "hard"),
    ("euhydration", ["正常水合"], 4, "hard"),
    ("sweat", ["汗液"], 5, "easy"),
    ("sodium", ["钠"], 5, "medium"),
    ("chloride", ["氯"], 4, "hard"),
    ("potassium", ["钾"], 5, "medium"),
    ("magnesium", ["镁"], 4, "hard"),
    ("calcium", ["钙"], 5, "medium"),
    ("cramp", ["痉挛"], 5, "easy"),
    ("heat", ["热"], 5, "easy"),
    ("exhaustion", ["衰竭"], 4, "hard"),
    ("stroke", ["中暑"], 4, "medium"),
    ("syncope", ["晕厥"], 4, "hard"),
    ("hypotension", ["低血压"], 4, "hard"),
    ("arrhythmia", ["心律失常"], 4, "hard"),
    ("sudden", ["突然的"], 4, "medium"),
    ("cardiac", ["心脏的"], 4, "hard"),
    ("death", ["死亡"], 4, "easy"),
    ("SCD", ["心源性猝死"], 5, "hard"),
    ("screening", ["筛查"], 5, "medium"),
    ("PAR-Q", ["体力活动准备问卷"], 5, "hard"),
    ("risk", ["风险"], 5, "easy"),
    ("stratification", ["分层"], 4, "hard"),
    ("contraindication", ["禁忌证"], 5, "hard"),
    ("precaution", ["预防措施"], 5, "medium"),
    ("relative", ["相对的"], 4, "medium"),
    ("absolute", ["绝对的"], 4, "medium"),
    ("comorbidity", ["合并症"], 4, "hard"),
    ("multimorbidity", ["多病共存"], 3, "hard"),
    ("frailty", ["衰弱"], 4, "hard"),
    ("sarcopenia", ["肌少症"], 5, "hard"),
    ("dynapenia", ["肌力缺乏"], 3, "hard"),
    ("osteopenia", ["骨量减少"], 4, "hard"),
    ("osteoporosis", ["骨质疏松"], 5, "hard"),
    ("osteopenia", ["骨量减少"], 4, "hard"),
    ("sarcopenic", ["肌少性"], 3, "hard"),
    ("obesity", ["肥胖"], 6, "hard"),
    ("diabetes", ["糖尿病"], 6, "hard"),
    ("mellitus", [" mellitus"], 4, "hard"),
    ("type", ["类型"], 5, "easy"),
    ("prediabetes", ["糖尿病前期"], 4, "hard"),
    ("gestational", ["妊娠的"], 4, "hard"),
    ("hypertension", ["高血压"], 5, "hard"),
    ("prehypertension", ["高血压前期"], 4, "hard"),
    ("dyslipidemia", ["血脂异常"], 4, "hard"),
    ("hyperlipidemia", ["高脂血症"], 4, "hard"),
    ("metabolic", ["代谢的"], 5, "hard"),
    ("syndrome", ["综合征"], 5, "medium"),
    ("MetS", ["代谢综合征"], 5, "hard"),
    ("atherosclerosis", ["动脉粥样硬化"], 4, "hard"),
    ("peripheral", ["外周的"], 4, "hard"),
    ("artery", ["动脉"], 4, "hard"),
    ("disease", ["疾病"], 5, "easy"),
    ("PAD", ["外周动脉疾病"], 4, "hard"),
    ("coronary", ["冠状动脉"], 4, "hard"),
    ("heart", ["心脏"], 5, "easy"),
    ("disease", ["疾病"], 5, "easy"),
    ("CHD", ["冠心病"], 5, "hard"),
    ("congestive", ["充血性"], 3, "hard"),
    ("heart", ["心力衰竭"], 4, "easy"),
    ("failure", ["衰竭"], 4, "medium"),
    ("chronic", ["慢性"], 4, "medium"),
    ("obstructive", ["阻塞性"], 4, "hard"),
    ("pulmonary", ["肺"], 4, "hard"),
    ("disease", ["疾病"], 4, "easy"),
    ("COPD", ["慢性阻塞性肺病"], 5, "hard"),
    ("asthma", ["哮喘"], 5, "hard"),
    ("bronchial", ["支气管"], 4, "hard"),
    ("hyperresponsiveness", ["高反应性"], 3, "hard"),
    ("exercise-induced", ["运动诱发"], 4, "hard"),
    ("bronchoconstriction", ["支气管收缩"], 3, "hard"),
    ("EIB", ["运动诱发支气管收缩"], 4, "hard"),
    ("cancer", ["癌症"], 5, "medium"),
    ("cachexia", ["恶病质"], 4, "hard"),
    ("anorexia", ["厌食"], 4, "hard"),
    ("depression", ["抑郁"], 5, "hard"),
    ("anxiety", ["焦虑"], 5, "hard"),
    ("cognitive", ["认知的"], 5, "hard"),
    ("decline", ["衰退"], 4, "medium"),
    ("dementia", ["痴呆"], 4, "hard"),
    ("Alzheimer", ["阿尔茨海默"], 4, "hard"),
    ("Parkinson", ["帕金森"], 4, "hard"),
    ("multiple", ["多发"], 4, "medium"),
    ("sclerosis", ["硬化"], 4, "hard"),
    ("MS", ["多发性硬化"], 4, "hard"),
    ("spinal", ["脊髓"], 4, "hard"),
    ("cord", [" cord"], 4, "easy"),
    ("injury", ["损伤"], 4, "easy"),
    ("SCI", ["脊髓损伤"], 4, "hard"),
    ("traumatic", ["创伤性"], 4, "hard"),
    ("brain", ["脑"], 4, "easy"),
    ("injury", ["损伤"], 4, "easy"),
    ("TBI", ["创伤性脑损伤"], 4, "hard"),
    ("cerebral", ["脑"], 4, "hard"),
    ("palsy", ["麻痹"], 4, "hard"),
    ("CP", ["脑瘫"], 4, "hard"),
    ("amputation", ["截肢"], 4, "hard"),
    ("prosthesis", ["假体"], 4, "hard"),
    ("orthosis", ["矫形器"], 4, "hard"),
    ("wheelchair", ["轮椅"], 4, "medium"),
    ("ambulatory", ["可行走的"], 4, "hard"),
    ("assistive", ["辅助的"], 4, "hard"),
    ("device", ["装置"], 4, "medium"),
    ("crutch", ["拐杖"], 4, "medium"),
    ("cane", ["手杖"], 4, "easy"),
    ("walker", ["助行器"], 4, "medium"),
    ("rollator", ["轮式助行器"], 3, "hard"),
    ("gait", ["步态"], 5, "hard"),
    ("trainer", ["训练器"], 4, "medium"),
    ("treadmill", ["跑步机"], 5, "medium"),
    ("anti-gravity", ["反重力"], 4, "hard"),
    ("alterG", [" AlterG"], 3, "hard"),
    ("aquatic", ["水疗"], 4, "hard"),
    ("therapy", ["治疗"], 5, "medium"),
    ("hydrotherapy", ["水疗"], 4, "hard"),
    ("balneotherapy", ["浴疗"], 3, "hard"),
    ("thalassotherapy", ["海水浴疗法"], 3, "hard"),
    ("cryotherapy", ["冷冻疗法"], 4, "hard"),
    ("contrast", ["对比"], 4, "medium"),
    ("bath", ["浴"], 4, "easy"),
    ("thermotherapy", ["热疗"], 4, "hard"),
    ("diathermy", ["透热疗法"], 3, "hard"),
    ("ultrasound", ["超声"], 4, "hard"),
    ("phonophoresis", ["超声透入"], 3, "hard"),
    ("electrical", ["电"], 4, "hard"),
    ("stimulation", ["刺激"], 4, "hard"),
    ("TENS", ["经皮神经电刺激"], 4, "hard"),
    ("NMES", ["神经肌肉电刺激"], 4, "hard"),
    ("FES", ["功能性电刺激"], 4, "hard"),
    ("Russian", ["俄式"], 4, "medium"),
    ("current", ["电流"], 4, "medium"),
    ("interferential", ["干扰"], 3, "hard"),
    ("premodulated", ["预调"], 3, "hard"),
    ("high-volt", ["高压"], 3, "hard"),
    ("pulsed", ["脉冲"], 4, "medium"),
    ("electromagnetic", ["电磁"], 4, "hard"),
    ("field", ["场"], 4, "easy"),
    ("PEMF", ["脉冲电磁场"], 3, "hard"),
    ("low-level", ["低强度"], 3, "hard"),
    ("laser", ["激光"], 4, "medium"),
    ("therapy", ["治疗"], 4, "medium"),
    ("LLLT", ["低强度激光疗法"], 3, "hard"),
    ("photobiomodulation", ["光生物调节"], 3, "hard"),
    ("shockwave", ["冲击波"], 4, "hard"),
    ("extracorporeal", ["体外"], 3, "hard"),
    ("ESWT", ["体外冲击波疗法"], 3, "hard"),
    ("radial", ["径向"], 3, "hard"),
    ("focused", ["聚焦"], 3, "hard"),
    ("dry", ["干"], 3, "easy"),
    ("needling", ["针刺"], 4, "hard"),
    ("acupuncture", ["针刺"], 4, "hard"),
    ("moxibustion", ["艾灸"], 4, "hard"),
    ("cupping", ["拔罐"], 4, "hard"),
    ("gua", ["刮痧"], 3, "hard"),
    ("sha", ["痧"], 3, "hard"),
    ("tui", ["推拿"], 3, "hard"),
    ("na", ["拿"], 3, "easy"),
    ("massage", ["按摩"], 5, "easy"),
    ("Swedish", ["瑞典式"], 4, "medium"),
    ("deep", ["深"], 4, "easy"),
    ("tissue", ["组织"], 4, "medium"),
    ("sports", ["运动"], 4, "easy"),
    ("myofascial", ["肌筋膜"], 4, "hard"),
    ("release", [" release", "释放"], 4, "medium"),
    ("MFR", ["肌筋膜释放"], 4, "hard"),
    ("trigger", ["触发"], 4, "medium"),
    ("point", ["点"], 4, "easy"),
    ("TP", ["触发点"], 4, "hard"),
    ("ischial", ["坐骨的"], 3, "hard"),
    ("band", ["束带"], 3, "easy"),
    ("IT", ["髂胫束"], 4, "hard"),
    ("foam", ["泡沫"], 4, "easy"),
    ("rolling", ["滚压"], 4, "medium"),
    ("self-myofascial", ["自我肌筋膜"], 3, "hard"),
    ("SMR", ["自我肌筋膜放松"], 4, "hard"),
    ("fascia", ["筋膜"], 4, "hard"),
    ("blaster", [" blaster"], 3, "hard"),
    ("muscle", ["肌肉"], 4, "easy"),
    ("scraper", [" scraper", "刮刀"], 3, "hard"),
    ("graston", ["格拉斯顿"], 3, "hard"),
    ("technique", ["技术"], 4, "medium"),
    ("IASTM", ["仪器辅助软组织松解"], 3, "hard"),
    ("active", ["主动的"], 4, "medium"),
    ("release", [" release"], 4, "medium"),
    ("ART", ["主动释放技术"], 4, "hard"),
    ("strain-counterstrain", ["应变-反应变"], 3, "hard"),
    ("muscle", ["肌肉"], 4, "easy"),
    ("energy", ["能量"], 4, "easy"),
    ("MET", ["肌肉能量技术"], 4, "hard"),
    ("proprioceptive", ["本体感觉"], 4, "hard"),
    ("neuromuscular", ["神经肌肉"], 4, "hard"),
    ("facilitation", ["促进"], 4, "hard"),
    ("PNF", ["本体感觉神经肌肉促进法"], 4, "hard"),
    ("hold-relax", ["保持-放松"], 4, "hard"),
    ("contract-relax", ["收缩-放松"], 4, "hard"),
    ("agonist", ["主动肌"], 4, "hard"),
    ("contract", ["收缩"], 4, "medium"),
    ("antagonist", ["拮抗肌"], 4, "hard"),
    ("facilitated", ["促进"], 3, "hard"),
    ("stretching", ["拉伸"], 4, "medium"),
    ("dynamic", ["动态"], 4, "medium"),
    ("ballistic", ["弹震式"], 4, "hard"),
    ("static", ["静态"], 4, "medium"),
    ("passive", ["被动"], 4, "medium"),
    ("active", ["主动"], 4, "medium"),
    ("assisted", ["辅助"], 4, "medium"),
    ("isometric", ["等长"], 4, "hard"),
    ("quadriceps", ["股四头肌"], 5, "hard"),
    ("setting", ["设定"], 4, "easy"),
    ("QS", ["股四头肌设定"], 4, "hard"),
    ("straight", ["直"], 4, "easy"),
    ("leg", ["腿"], 4, "easy"),
    ("raise", ["抬高"], 4, "medium"),
    ("SLR", ["直腿抬高"], 4, "hard"),
    ("bracing", ["支具"], 4, "hard"),
    ("taping", ["贴扎"], 4, "hard"),
    ("kinesiology", ["肌内效"], 4, "hard"),
    ("KT", ["肌内效贴"], 4, "hard"),
    ("McConnell", ["麦克康奈尔"], 3, "hard"),
    ("Mulligan", ["穆里根"], 3, "hard"),
    ("mobilization", ["松动"], 4, "hard"),
    ("Maitland", ["梅特兰"], 3, "hard"),
    ("Kaltenborn", ["卡尔滕博恩"], 3, "hard"),
    ("Cyriax", ["西里克斯"], 3, "hard"),
    ("osteopathic", ["整骨"], 3, "hard"),
    ("chiropractic", ["脊骨神经医学"], 3, "hard"),
    ("manipulation", ["手法"], 4, "hard"),
    ("HVLA", ["高速低幅"], 3, "hard"),
    ("joint", ["关节"], 4, "easy"),
    ("mobilization", ["松动"], 4, "hard"),
    ("MWM", ["动态关节松动"], 3, "hard"),
    ("SNAG", ["持续自然关节松动"], 3, "hard"),
    ("REVERSE", ["反向"], 3, "easy"),
    ("SNAG", ["反向持续自然关节松动"], 3, "hard"),
    ("BIONT", ["生理性关节松动"], 3, "hard"),
    ("distraction", ["分离"], 4, "hard"),
    ("glide", ["滑动"], 4, "medium"),
    ("traction", ["牵引"], 4, "hard"),
    ("compression", ["加压"], 4, "hard"),
    ("oscillation", ["摆动"], 4, "hard"),
    ("grade", ["级别"], 4, "easy"),
    ("I-IV", ["I-IV级"], 3, "hard"),
    ("accessory", ["附属"], 3, "hard"),
    ("movement", ["运动"], 4, "easy"),
    ("physiological", ["生理性的"], 3, "hard"),
    ("movement", ["运动"], 4, "easy"),
    ("arthrokinematics", ["关节运动学"], 3, "hard"),
    ("osteokinematics", ["骨骼运动学"], 3, "hard"),
    ("concave", ["凹"], 3, "hard"),
    ("convex", ["凸"], 3, "hard"),
    ("rule", ["规则"], 4, "easy"),
    ("convex-concave", ["凹凸规则"], 3, "hard"),
    ("roll", ["滚动"], 3, "easy"),
    ("slide", ["滑动"], 3, "easy"),
    ("spin", ["旋转"], 3, "easy"),
    ("close-pack", ["紧密位"], 3, "hard"),
    ("position", ["位置"], 4, "easy"),
    ("CPP", ["紧密位"], 3, "hard"),
    ("open-pack", ["松弛位"], 3, "hard"),
    ("resting", ["休息位"], 3, "medium"),
    ("position", ["位置"], 3, "easy"),
    ("RPP", ["松弛位"], 3, "hard"),
    ("capsular", ["关节囊"], 3, "hard"),
    ("pattern", ["模式"], 4, "easy"),
    ("CP", ["关节囊模式"], 3, "hard"),
    ("loose", ["松的"], 3, "easy"),
    ("tight", ["紧的"], 3, "easy"),
    ("end", ["终末"], 3, "easy"),
    ("feel", ["感觉"], 3, "easy"),
    ("hard", ["硬的"], 3, "easy"),
    ("soft", ["软的"], 3, "easy"),
    ("capsular", ["囊性"], 3, "hard"),
    ("end-feel", ["终末感"], 3, "hard"),
    ("bone-to-bone", ["骨对骨"], 3, "hard"),
    ("soft-tissue", ["软组织"], 3, "hard"),
    ("approximation", ["靠近"], 3, "hard"),
    ("tissue", ["组织"], 3, "medium"),
    ("stretch", ["拉伸"], 3, "easy"),
    ("muscle", ["肌肉"], 3, "easy"),
    ("guard", ["保护"], 3, "easy"),
    ("empty", ["空的"], 3, "easy"),
    ("end-feel", ["空虚终末感"], 3, "hard"),
    ("spring", ["弹性"], 3, "easy"),
    ("block", ["阻滞"], 3, "easy"),
    ("hypermobile", ["活动过度"], 3, "hard"),
    ("hypomobile", ["活动不足"], 3, "hard"),
    ("instability", ["不稳"], 3, "hard"),
    ("laxity", ["松弛"], 3, "hard"),
    ("translation", ["平移"], 3, "hard"),
    ("anterior", ["前侧"], 3, "medium"),
    ("drawer", ["抽屉"], 3, "easy"),
    ("test", [" test", "测试"], 3, "easy"),
    ("ADT", ["前抽屉测试"], 3, "hard"),
    ("posterior", ["后侧"], 3, "medium"),
    ("drawer", ["抽屉"], 3, "easy"),
    ("PDT", ["后抽屉测试"], 3, "hard"),
    ("Lachman", ["拉赫曼"], 3, "hard"),
    ("pivot", ["轴移"], 3, "medium"),
    ("shift", ["移位"], 3, "medium"),
    ("McMurray", ["麦克默里"], 3, "hard"),
    ("Apley", ["阿普利"], 3, "hard"),
    ("grind", ["研磨"], 3, "easy"),
    ("compression", ["加压"], 3, "hard"),
    ("apprehension", ["恐惧"], 3, "hard"),
    ("test", [" test"], 3, "easy"),
    (" relocation", ["复位"], 3, "medium"),
    ("test", [" test"], 3, "easy"),
    ("sulcus", ["沟"], 3, "hard"),
    ("sign", [" sign", "征"], 3, "easy"),
    ("load", ["负荷"], 3, "easy"),
    ("shift", ["移位"], 3, "medium"),
    ("test", [" test"], 3, "easy"),
    ("O'Brien", ["奥布莱恩"], 3, "hard"),
    ("Speed", ["斯皮德"], 3, "hard"),
    ("Yergason", ["耶加森"], 3, "hard"),
    ("Cozen's", ["科岑"], 3, "hard"),
    ("Mill", ["米尔"], 3, "hard"),
    ("Maudsley", ["莫兹利"], 3, "hard"),
    ("Phalen", ["菲伦"], 3, "hard"),
    ("Tinel", ["蒂内尔"], 3, "hard"),
    ("Finkelstein", ["芬克尔斯坦"], 3, "hard"),
    ("Thomas", ["托马斯"], 3, "hard"),
    ("Ober", ["奥伯"], 3, "hard"),
    ("Phelps", ["菲尔普斯"], 3, "hard"),
    ("Ely", ["伊利"], 3, "hard"),
    ("Stinchfield", ["斯廷奇菲尔德"], 3, "hard"),
    ("Craig", ["克雷格"], 3, "hard"),
    ("test", [" test"], 3, "easy"),
    ("Scour", ["擦洗"], 3, "hard"),
    ("FABER", [" FABER", "屈曲外展外旋伸展"], 3, "hard"),
    ("FAIR", [" FAIR", "屈曲内收内旋"], 3, "hard"),
    ("FADIR", [" FADIR", "屈曲内收内旋"], 3, "hard"),
    ("Stork", ["鹳"], 3, "hard"),
    ("Trendelenburg", ["特伦德伦堡"], 3, "hard"),
    ("sign", [" sign"], 3, "easy"),
    ("Single-leg", ["单腿"], 3, "hard"),
    ("squat", ["深蹲"], 3, "medium"),
    ("test", [" test"], 3, "easy"),
    ("Star", ["星形"], 3, "hard"),
    ("Excursion", ["偏移"], 3, "hard"),
    ("Balance", ["平衡"], 3, "medium"),
    ("Test", ["测试"], 3, "easy"),
    ("SEBT", ["星形偏移平衡测试"], 3, "hard"),
    ("Y-balance", ["Y平衡"], 3, "hard"),
    ("test", [" test"], 3, "easy"),
    ("Hop", ["跳跃"], 3, "easy"),
    ("test", [" test"], 3, "easy"),
    ("single-leg", ["单腿"], 3, "hard"),
    ("triple", ["三重"], 3, "easy"),
    ("crossover", ["交叉"], 3, "medium"),
    ("6-meter", ["6米"], 3, "hard"),
    ("timed", ["计时"], 3, "medium"),
    ("T-test", ["T测试"], 3, "hard"),
    (" Illinois", ["伊利诺伊"], 3, "hard"),
    ("agility", ["敏捷"], 3, "hard"),
    ("test", [" test"], 3, "easy"),
    ("pro-agility", ["职业敏捷"], 3, "hard"),
    ("5-10-5", ["5-10-5"], 3, "hard"),
    ("shuttle", ["往返"], 3, "medium"),
    ("run", ["跑"], 3, "easy"),
    ("beep", ["哔"], 3, "easy"),
    ("test", [" test"], 3, "easy"),
    ("yo-yo", ["悠悠"], 3, "hard"),
    ("intermittent", ["间歇"], 3, "hard"),
    ("recovery", ["恢复"], 3, "medium"),
    ("test", [" test"], 3, "easy"),
    ("level", ["水平"], 3, "easy"),
    ("1", ["1级"], 3, "easy"),
    ("2", ["2级"], 3, "easy"),
    ("sit-and-reach", ["坐位体前屈"], 3, "hard"),
    ("back-scratch", ["后背抓"], 3, "hard"),
    ("shoulder", ["肩"], 3, "medium"),
    ("flexibility", ["柔韧"], 3, "hard"),
    ("test", [" test"], 3, "easy"),
    ("goniometer", ["量角器"], 3, "hard"),
    ("goniometry", ["测角法"], 3, "hard"),
    ("inclinometer", ["测斜仪"], 3, "hard"),
    ("universal", ["通用"], 3, "medium"),
    ("digital", ["数字"], 3, "medium"),
    ("smartphone", ["智能手机"], 3, "easy"),
    ("app", ["应用"], 3, "easy"),
    ("accelerometer", ["加速度计"], 3, "hard"),
    ("gyroscope", ["陀螺仪"], 3, "hard"),
    ("IMU", ["惯性测量单元"], 3, "hard"),
    ("GPS", ["全球定位系统"], 3, "hard"),
    ("wearable", ["可穿戴"], 3, "medium"),
    ("device", ["设备"], 3, "medium"),
    ("smartwatch", ["智能手表"], 3, "medium"),
    ("fitness", ["健身"], 3, "easy"),
    ("tracker", ["追踪器"], 3, "medium"),
    ("heart", ["心率"], 3, "easy"),
    ("monitor", ["监测"], 3, "medium"),
    ("chest", ["胸带"], 3, "easy"),
    ("strap", [" strap"], 3, "easy"),
    ("optical", ["光学"], 3, "hard"),
    ("sensor", ["传感器"], 3, "medium"),
    ("PPG", ["光电容积描记"], 3, "hard"),
    ("ECG", ["心电图"], 3, "hard"),
    ("HRV", ["心率变异性"], 3, "hard"),
    ("RHR", ["静息心率"], 3, "hard"),
    ("MHR", ["最大心率"], 3, "hard"),
    ("THR", ["靶心率"], 3, "hard"),
    ("HRmax", ["最大心率"], 3, "hard"),
    ("HRrest", ["静息心率"], 3, "hard"),
    ("HRreserve", ["心率储备"], 3, "hard"),
    ("%HRR", ["心率储备百分比"], 3, "hard"),
    ("%HRmax", ["最大心率百分比"], 3, "hard"),
    ("Karvonen", ["卡沃宁"], 3, "hard"),
    ("formula", ["公式"], 3, "medium"),
    ("Tanaka", ["田中"], 3, "hard"),
    ("formula", ["公式"], 3, "medium"),
    ("Gellish", ["盖利什"], 3, "hard"),
    ("formula", ["公式"], 3, "medium"),
    ("Nes", ["内斯"], 3, "hard"),
    ("formula", ["公式"], 3, "medium"),
    ("Robergs", ["罗伯茨"], 3, "hard"),
    ("Landwehr", ["兰德韦尔"], 3, "hard"),
    ("formula", ["公式"], 3, "medium"),
    ("Fox", ["福克斯"], 3, "hard"),
    ("formula", ["公式"], 3, "medium"),
    ("220-age", ["220-年龄"], 3, "hard"),
    ("208-0.7xage", ["208-0.7x年龄"], 3, "hard"),
    ("207-0.7xage", ["207-0.7x年龄"], 3, "hard"),
    ("ACSM", ["美国运动医学学会"], 5, "hard"),
    ("guideline", ["指南"], 4, "medium"),
    ("position", ["立场"], 4, "easy"),
    ("stand", [" stand", "立场"], 4, "easy"),
    ("consensus", ["共识"], 4, "hard"),
    ("statement", ["声明"], 4, "medium"),
    ("round", [" round", "轮"], 3, "easy"),
    ("table", ["圆桌"], 3, "easy"),
    ("expert", ["专家"], 3, "medium"),
    ("panel", [" panel", "专家组"], 3, "medium"),
    ("evidence-based", ["循证"], 3, "hard"),
    ("practice", ["实践"], 3, "medium"),
    ("clinical", ["临床"], 3, "medium"),
    ("guideline", ["指南"], 3, "medium"),
    ("systematic", ["系统"], 3, "hard"),
    ("review", ["综述"], 3, "medium"),
    ("meta-analysis", ["荟萃分析"], 3, "hard"),
    ("randomized", ["随机"], 3, "hard"),
    ("controlled", ["对照"], 3, "medium"),
    ("trial", ["试验"], 3, "medium"),
    ("RCT", ["随机对照试验"], 3, "hard"),
    ("cohort", ["队列"], 3, "hard"),
    ("study", ["研究"], 3, "easy"),
    ("cross-sectional", ["横断面"], 3, "hard"),
    ("longitudinal", ["纵向"], 3, "hard"),
    ("prospective", ["前瞻性"], 3, "hard"),
    ("retrospective", ["回顾性"], 3, "hard"),
    ("case-control", ["病例对照"], 3, "hard"),
    ("case", ["病例"], 3, "easy"),
    ("series", ["系列"], 3, "easy"),
    ("case", ["病例"], 3, "easy"),
    ("report", ["报告"], 3, "easy"),
    ("pilot", [" pilot", "试点"], 3, "medium"),
    ("study", ["研究"], 3, "easy"),
    ("feasibility", ["可行性"], 3, "hard"),
    ("study", ["研究"], 3, "easy"),
    ("protocol", ["方案"], 3, "medium"),
    ("CONSORT", [" CONSORT", "统一报告标准"], 3, "hard"),
    ("PRISMA", [" PRISMA", "系统综述优先报告条目"], 3, "hard"),
    ("STROBE", [" STROBE", "加强流行病学观察性研究报告"], 3, "hard"),
    ("CARE", [" CARE", "病例报告指南"], 3, "hard"),
    ("SPIRIT", [" SPIRIT", "标准方案项目"], 3, "hard"),
    ("PROSPERO", [" PROSPERO", "系统综述注册平台"], 3, "hard"),
    ("PEDro", [" PEDro", "物理治疗证据数据库"], 3, "hard"),
    ("scale", ["量表"], 3, "medium"),
    ("COSMIN", [" COSMIN", "测量工具选择标准"], 3, "hard"),
    ("checklist", ["清单"], 3, "medium"),
    ("MINORS", [" MINORS", "非随机研究方法学指标"], 3, "hard"),
    ("NOS", [" NOS", "纽卡斯尔-渥太华量表"], 3, "hard"),
    ("ROB", [" ROB", "偏倚风险"], 3, "hard"),
    ("Cochrane", ["科克伦"], 3, "hard"),
    ("risk", ["风险"], 3, "easy"),
    ("tool", ["工具"], 3, "easy"),
    ("RoB", ["偏倚风险"], 3, "hard"),
    ("2", ["2.0"], 3, "easy"),
    ("GRADE", [" GRADE", "推荐分级的评估、制定与评价"], 3, "hard"),
    ("approach", ["方法"], 3, "medium"),
    ("certainty", ["确定性"], 3, "hard"),
    ("evidence", ["证据"], 3, "medium"),
    ("high", ["高"], 3, "easy"),
    ("moderate", ["中等"], 3, "easy"),
    ("low", ["低"], 3, "easy"),
    ("very", ["非常"], 3, "easy"),
    ("low", ["低"], 3, "easy"),
    ("number", ["数量"], 3, "easy"),
    ("needed", ["需要"], 3, "easy"),
    ("treat", ["治疗"], 3, "easy"),
    ("NNT", ["需治疗人数"], 3, "hard"),
    ("harm", ["伤害"], 3, "easy"),
    ("NNH", ["需伤害人数"], 3, "hard"),
    ("effect", ["效应"], 3, "medium"),
    ("size", ["大小"], 3, "easy"),
    ("Cohen", ["科恩"], 3, "hard"),
    ("d", ["d值"], 3, "easy"),
    (" Hedge", [" Hedge", " Hedge"], 3, "hard"),
    ("g", ["g值"], 3, "easy"),
    (" odds", [" odds", "比值"], 3, "hard"),
    ("ratio", ["比值"], 3, "medium"),
    ("OR", ["比值比"], 3, "hard"),
    ("relative", ["相对"], 3, "medium"),
    ("risk", ["风险"], 3, "easy"),
    ("RR", ["相对危险度"], 3, "hard"),
    ("absolute", ["绝对"], 3, "medium"),
    ("risk", ["风险"], 3, "easy"),
    ("reduction", ["降低"], 3, "medium"),
    ("ARR", ["绝对风险降低"], 3, "hard"),
    ("relative", ["相对"], 3, "medium"),
    ("risk", ["风险"], 3, "easy"),
    ("reduction", ["降低"], 3, "medium"),
    ("RRR", ["相对风险降低"], 3, "hard"),
    ("confidence", ["置信"], 3, "hard"),
    ("interval", ["区间"], 3, "medium"),
    ("CI", ["置信区间"], 3, "hard"),
    ("95%", ["95%"], 3, "easy"),
    ("p-value", ["p值"], 3, "hard"),
    ("alpha", ["α"], 3, "hard"),
    ("level", ["水平"], 3, "easy"),
    ("beta", ["β"], 3, "hard"),
    ("power", ["效能"], 3, "easy"),
    ("sample", ["样本"], 3, "medium"),
    ("size", ["大小"], 3, "easy"),
    ("calculation", ["计算"], 3, "medium"),
    ("intention-to-treat", ["意向性治疗"], 3, "hard"),
    ("per-protocol", ["符合方案"], 3, "hard"),
    ("as-treated", ["实际治疗"], 3, "hard"),
    ("allocation", ["分配"], 3, "hard"),
    ("concealment", ["隐藏"], 3, "hard"),
    ("blinding", ["盲法"], 3, "hard"),
    ("masking", ["遮蔽"], 3, "hard"),
    ("single-blind", ["单盲"], 3, "hard"),
    ("double-blind", ["双盲"], 3, "hard"),
    ("triple-blind", ["三盲"], 3, "hard"),
    ("open-label", ["开放标签"], 3, "hard"),
    ("placebo", ["安慰剂"], 3, "hard"),
    ("sham", ["假"], 3, "hard"),
    ("control", ["对照"], 3, "medium"),
    ("waitlist", ["等待名单"], 3, "hard"),
    ("usual", ["常规"], 3, "medium"),
    ("care", [" care", "护理"], 3, "easy"),
    ("minimal", ["最小"], 3, "medium"),
    ("intervention", ["干预"], 3, "medium"),
    ("attention", ["注意"], 3, "medium"),
    ("control", ["对照"], 3, "medium"),
    ("no-treatment", ["无治疗"], 3, "hard"),
    ("dose-response", ["剂量-反应"], 3, "hard"),
    ("relationship", ["关系"], 3, "medium"),
    ("minimal", ["最小"], 3, "medium"),
    ("clinically", ["临床"], 3, "hard"),
    ("important", ["重要"], 3, "easy"),
    ("difference", ["差异"], 3, "medium"),
    ("CID", ["临床重要差异"], 3, "hard"),
    ("MCID", ["最小临床重要差异"], 3, "hard"),
    ("MID", ["重要差异"], 3, "hard"),
    ("SD", ["标准差"], 3, "hard"),
    ("SEM", ["标准误"], 3, "hard"),
    ("MDC", ["最小可检测变化"], 3, "hard"),
    ("SRM", ["标准化反应均数"], 3, "hard"),
    ("ES", ["效应量"], 3, "hard"),
    ("ICC", ["组内相关系数"], 3, "hard"),
    ("Cronbach", ["克朗巴赫"], 3, "hard"),
    ("alpha", ["α系数"], 3, "hard"),
    ("test-retest", ["重测"], 3, "hard"),
    ("reliability", ["信度"], 3, "hard"),
    ("inter-rater", ["评定者间"], 3, "hard"),
    ("intra-rater", ["评定者内"], 3, "hard"),
    ("validity", ["效度"], 3, "hard"),
    ("content", ["内容"], 3, "easy"),
    ("criterion", ["标准"], 3, "medium"),
    ("concurrent", ["同时"], 3, "hard"),
    ("predictive", ["预测"], 3, "hard"),
    ("construct", ["结构"], 3, "hard"),
    ("convergent", ["聚合"], 3, "hard"),
    ("divergent", ["发散"], 3, "hard"),
    ("discriminant", ["区分"], 3, "hard"),
    ("known-groups", ["已知群体"], 3, "hard"),
    ("responsiveness", ["反应性"], 3, "hard"),
    ("floor", [" floor", "地板"], 3, "easy"),
    ("ceiling", ["天花板"], 3, "easy"),
    ("effect", ["效应"], 3, "medium"),
    ("floor", ["地板效应"], 3, "hard"),
    ("ceiling", ["天花板效应"], 3, "hard"),
    ("normative", ["常模"], 3, "hard"),
    ("data", ["数据"], 3, "easy"),
    ("reference", ["参考"], 3, "medium"),
    ("value", ["值"], 3, "easy"),
    ("percentile", ["百分位"], 3, "hard"),
    ("z-score", ["z分数"], 3, "hard"),
    ("t-score", ["t分数"], 3, "hard"),
    ("stanine", ["九分制"], 3, "hard"),
    ("normal", ["正常"], 3, "easy"),
    ("distribution", ["分布"], 3, "medium"),
    ("bell", [" bell", "钟形"], 3, "easy"),
    ("curve", ["曲线"], 3, "easy"),
    ("skewness", ["偏度"], 3, "hard"),
    ("kurtosis", ["峰度"], 3, "hard"),
    ("heteroscedasticity", ["异方差"], 3, "hard"),
    ("homoscedasticity", ["同方差"], 3, "hard"),
    ("multicollinearity", ["多重共线性"], 3, "hard"),
    ("VIF", ["方差膨胀因子"], 3, "hard"),
    ("outlier", ["异常值"], 3, "hard"),
    ("missing", ["缺失"], 3, "medium"),
    ("data", ["数据"], 3, "easy"),
    ("imputation", ["插补"], 3, "hard"),
    ("last", ["最后"], 3, "easy"),
    ("observation", ["观察"], 3, "medium"),
    ("carried", ["携带"], 3, "easy"),
    ("forward", ["向前"], 3, "easy"),
    ("LOCF", ["末次观测值结转"], 3, "hard"),
    ("multiple", ["多重"], 3, "medium"),
    ("imputation", ["插补"], 3, "hard"),
    ("MI", ["多重插补"], 3, "hard"),
]

# 领域8: 生物力学与测量 (~100词)
biomech = [
    ("biomechanics", ["生物力学"], 7, "hard"),
    ("kinetics", ["动力学"], 5, "hard"),
    ("kinematics", ["运动学"], 5, "hard"),
    ("statics", ["静力学"], 5, "hard"),
    ("dynamics", ["动力学"], 5, "hard"),
    ("force", ["力"], 9, "easy"),
    ("vector", ["矢量"], 5, "hard"),
    ("scalar", ["标量"], 4, "hard"),
    ("magnitude", ["大小"], 5, "medium"),
    ("direction", ["方向"], 6, "easy"),
    ("velocity", ["速度"], 7, "medium"),
    ("acceleration", ["加速度"], 6, "hard"),
    ("deceleration", ["减速度"], 5, "hard"),
    ("displacement", ["位移"], 5, "hard"),
    ("distance", ["距离"], 7, "easy"),
    ("position", ["位置"], 7, "easy"),
    ("time", ["时间"], 8, "easy"),
    ("gravity", ["重力"], 6, "easy"),
    ("friction", ["摩擦力"], 6, "medium"),
    ("drag", ["阻力"], 5, "easy"),
    ("buoyancy", ["浮力"], 4, "hard"),
    ("lift", ["升力"], 5, "easy"),
    ("thrust", ["推力"], 4, "medium"),
    ("torque", ["扭矩"], 6, "hard"),
    ("moment", ["力矩"], 6, "medium"),
    ("arm", ["力臂"], 6, "easy"),
    ("lever", ["杠杆"], 5, "medium"),
    ("fulcrum", ["支点"], 4, "medium"),
    ("effort", ["作用力"], 5, "medium"),
    ("resistance", ["阻力"], 6, "medium"),
    ("mechanical", ["机械的"], 5, "hard"),
    ("advantage", ["优势"], 5, "medium"),
    ("MA", ["机械效益"], 5, "hard"),
    ("first-class", ["第一类"], 4, "hard"),
    ("second-class", ["第二类"], 4, "hard"),
    ("third-class", ["第三类"], 4, "hard"),
    ("work", ["功"], 7, "easy"),
    ("energy", ["能量"], 7, "easy"),
    ("power", ["功率"], 7, "easy"),
    ("efficiency", ["效率"], 6, "medium"),
    ("impulse", ["冲量"], 5, "hard"),
    ("momentum", ["动量"], 5, "hard"),
    ("conservation", ["守恒"], 5, "hard"),
    ("collision", ["碰撞"], 4, "medium"),
    ("elastic", ["弹性的"], 5, "medium"),
    ("inelastic", ["非弹性的"], 4, "hard"),
    ("coefficient", ["系数"], 5, "hard"),
    ("restitution", ["恢复"], 4, "hard"),
    ("COR", ["恢复系数"], 4, "hard"),
    ("center", ["中心"], 6, "easy"),
    ("mass", ["质量"], 6, "easy"),
    ("COM", ["质心"], 5, "hard"),
    ("gravity", ["重心"], 5, "easy"),
    ("COG", ["重心"], 5, "hard"),
    ("pressure", ["压力"], 6, "easy"),
    ("COP", ["压力中心"], 5, "hard"),
    ("base", ["基底"], 5, "easy"),
    ("support", ["支撑"], 6, "easy"),
    ("BOS", ["支撑面"], 5, "hard"),
    ("stability", ["稳定性"], 6, "hard"),
    ("balance", ["平衡"], 7, "medium"),
    ("postural", ["姿势的"], 5, "hard"),
    ("sway", ["摇摆"], 5, "medium"),
    ("equilibrium", ["平衡"], 5, "hard"),
    ("stable", ["稳定的"], 5, "easy"),
    ("unstable", ["不稳定的"], 4, "medium"),
    ("neutral", ["中性的"], 4, "medium"),
    ("ground", ["地面"], 6, "easy"),
    ("reaction", ["反作用力"], 6, "medium"),
    ("GRF", ["地面反作用力"], 6, "hard"),
    ("vertical", ["垂直的"], 5, "medium"),
    ("horizontal", ["水平的"], 5, "medium"),
    ("anterior-posterior", ["前后"], 4, "hard"),
    ("medial-lateral", ["内外侧"], 4, "hard"),
    ("free-body", ["自由体"], 4, "hard"),
    ("diagram", ["图解"], 5, "medium"),
    ("FBD", ["自由体图"], 4, "hard"),
    ("newton", ["牛顿"], 5, "hard"),
    ("first", ["第一"], 5, "easy"),
    ("second", ["第二"], 5, "easy"),
    ("third", ["第三"], 5, "easy"),
    ("law", ["定律"], 6, "easy"),
    ("motion", ["运动"], 6, "easy"),
    ("inertia", ["惯性"], 5, "hard"),
    ("acceleration", ["加速度"], 5, "hard"),
    ("action", ["作用力"], 5, "easy"),
    ("reaction", ["反作用力"], 5, "medium"),
    ("EMG", ["肌电图"], 6, "hard"),
    ("electromyography", ["肌电图"], 5, "hard"),
    ("sEMG", ["表面肌电图"], 5, "hard"),
    ("amplitude", ["振幅"], 5, "hard"),
    ("frequency", ["频率"], 5, "easy"),
    ("spectrum", ["频谱"], 4, "hard"),
    ("analysis", ["分析"], 5, "medium"),
    ("median", ["中位"], 4, "medium"),
    ("MF", ["中位频率"], 4, "hard"),
    ("mean", ["平均"], 4, "easy"),
    ("MNF", ["平均频率"], 4, "hard"),
    ("root", ["均方根"], 4, "easy"),
    ("mean", ["平均"], 4, "easy"),
    ("square", ["平方"], 4, "easy"),
    ("RMS", ["均方根振幅"], 5, "hard"),
    ("integrated", ["积分"], 4, "hard"),
    ("iEMG", ["积分肌电值"], 4, "hard"),
    ("normalized", ["标准化的"], 4, "hard"),
    ("MVC", ["最大自主收缩"], 5, "hard"),
    ("isokinetic", ["等速"], 5, "hard"),
    ("dynamometry", ["测力法"], 4, "hard"),
    ("peak", ["峰值"], 5, "easy"),
    ("torque", ["扭矩"], 5, "hard"),
    ("PT", ["峰值扭矩"], 5, "hard"),
    ("average", ["平均"], 5, "easy"),
    ("power", ["功率"], 5, "easy"),
    ("AP", ["平均功率"], 4, "hard"),
    ("work", ["功"], 5, "easy"),
    ("total", ["总"], 5, "easy"),
    ("TW", ["总功"], 4, "hard"),
    ("fatigue", ["疲劳"], 5, "easy"),
    ("index", ["指数"], 5, "easy"),
    ("FI", ["疲劳指数"], 4, "hard"),
    ("agonist", ["主动肌"], 5, "hard"),
    ("antagonist", ["拮抗肌"], 5, "hard"),
    ("ratio", ["比值"], 4, "medium"),
    ("HAMQ", ["腘绳肌/股四头肌比值"], 4, "hard"),
    ("deficit", [" deficit", "不足"], 4, "medium"),
    ("bilateral", ["双侧"], 4, "hard"),
    ("BDI", ["双侧缺陷指数"], 4, "hard"),
    ("limb", ["肢体"], 5, "easy"),
    ("symmetry", ["对称"], 4, "hard"),
    ("index", ["指数"], 4, "easy"),
    ("LSI", ["肢体对称指数"], 4, "hard"),
    ("ROM", ["关节活动度"], 7, "hard"),
    ("goniometry", ["测角法"], 4, "hard"),
    ("inclinometer", ["测斜仪"], 4, "hard"),
    ("flexion", ["屈曲"], 5, "hard"),
    ("extension", ["伸展"], 5, "hard"),
    ("abduction", ["外展"], 5, "hard"),
    ("adduction", ["内收"], 5, "hard"),
    ("rotation", ["旋转"], 5, "medium"),
    ("internal", ["内旋"], 4, "medium"),
    ("external", ["外旋"], 4, "medium"),
    ("circumduction", ["环转"], 4, "hard"),
    ("protraction", ["前伸"], 4, "hard"),
    ("retraction", ["回缩"], 4, "hard"),
    ("elevation", ["上提"], 4, "hard"),
    ("depression", ["下降"], 4, "hard"),
    ("inversion", ["内翻"], 4, "hard"),
    ("eversion", ["外翻"], 4, "hard"),
    ("pronation", ["旋前"], 4, "hard"),
    ("supination", ["旋后"], 4, "hard"),
    ("dorsiflexion", ["背屈"], 4, "hard"),
    ("plantarflexion", ["跖屈"], 4, "hard"),
    ("retraction", ["后缩"], 4, "hard"),
]

# 合并所有词
supplement = [
    ("plyometrics", ["增强式训练", "超等长训练"], 5, "hard"),
    ("stretch-shortening", ["牵张-缩短"], 5, "hard"),
    ("cycle", ["周期"], 5, "easy"),
    ("SSC", ["牵张-缩短周期"], 5, "hard"),
    ("countermovement", ["反向跳"], 4, "hard"),
    ("jump", ["跳跃"], 6, "easy"),
    ("CMJ", ["反向跳"], 5, "hard"),
    ("squat", ["深蹲跳"], 5, "medium"),
    ("jump", ["跳"], 5, "easy"),
    ("SJ", ["深蹲跳"], 4, "hard"),
    ("drop", ["下落"], 5, "easy"),
    ("jump", ["跳"], 5, "easy"),
    ("DJ", ["下落跳"], 4, "hard"),
    ("reactive", ["反应"], 4, "medium"),
    ("strength", ["力量"], 5, "easy"),
    ("index", ["指数"], 4, "easy"),
    ("RSI", ["反应力量指数"], 4, "hard"),
    ("contact", ["接触"], 4, "medium"),
    ("time", ["时间"], 4, "easy"),
    ("flight", ["腾空"], 4, "easy"),
    ("height", ["高度"], 4, "easy"),
    ("rate", ["速率"], 4, "easy"),
    ("force", ["力"], 5, "easy"),
    ("development", ["发展"], 4, "medium"),
    ("RFD", ["力量发展速率"], 4, "hard"),
    ("impulse", ["冲量"], 4, "hard"),
    ("momentum", ["动量"], 4, "hard"),
    ("angular", ["角"], 4, "hard"),
    ("velocity", ["速度"], 4, "medium"),
    ("tangential", ["切向"], 3, "hard"),
    ("radial", ["径向"], 3, "hard"),
    ("centripetal", ["向心"], 3, "hard"),
    ("centrifugal", ["离心"], 3, "hard"),
    ("force", ["力"], 3, "easy"),
    ("angular", ["角"], 3, "hard"),
    ("acceleration", ["加速度"], 3, "hard"),
    ("moment", ["矩"], 4, "medium"),
    ("inertia", ["惯性"], 4, "hard"),
    ("polar", ["极"], 3, "hard"),
    ("radius", ["半径"], 4, "medium"),
    ("gyration", ["回转"], 3, "hard"),
    ("segmental", ["节段"], 3, "hard"),
    ("analysis", ["分析"], 3, "medium"),
    ("kinematic", ["运动"], 3, "hard"),
    ("chain", ["链"], 3, "easy"),
    ("link", [" link", "环节"], 3, "easy"),
    ("model", ["模型"], 3, "medium"),
    ("inverse", ["逆"], 3, "hard"),
    ("dynamics", ["动力学"], 3, "hard"),
    ("forward", ["正向"], 3, "easy"),
    ("dynamics", ["动力学"], 3, "hard"),
    ("optimization", ["优化"], 3, "hard"),
    ("EMG-driven", ["肌电驱动"], 3, "hard"),
    ("musculoskeletal", ["肌肉骨骼"], 3, "hard"),
    ("modelling", ["建模"], 3, "hard"),
    ("AnyBody", [" AnyBody", " anybody"], 3, "hard"),
    ("OpenSim", [" OpenSim"], 3, "hard"),
    ("SIMM", [" SIMM"], 3, "hard"),
    ("Muscle", ["肌肉"], 3, "easy"),
    ("Redundancy", ["冗余"], 3, "hard"),
    ("Problem", ["问题"], 3, "easy"),
    ("MRP", ["肌肉冗余问题"], 3, "hard"),
    ("optimization", ["优化"], 3, "hard"),
    ("criterion", ["标准"], 3, "medium"),
    ("physiological", ["生理"], 3, "hard"),
    ("minimization", ["最小化"], 3, "hard"),
    ("sum", ["总和"], 3, "easy"),
    ("squared", ["平方"], 3, "easy"),
    ("muscle", ["肌肉"], 3, "easy"),
    ("activations", ["激活"], 3, "hard"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("individual", ["个体"], 3, "medium"),
    ("muscle", ["肌肉"], 3, "easy"),
    ("forces", ["力"], 3, "easy"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("muscle", ["肌肉"], 3, "easy"),
    ("stress", ["应力"], 3, "easy"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("muscle", ["肌肉"], 3, "easy"),
    ("fatigue", ["疲劳"], 3, "easy"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("endurance", ["耐力"], 3, "medium"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("joint", ["关节"], 3, "easy"),
    ("contact", ["接触"], 3, "medium"),
    ("force", ["力"], 3, "easy"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("joint", ["关节"], 3, "easy"),
    ("loading", ["负荷"], 3, "medium"),
    ("minimize", ["最小"], 3, "medium"),
    ("maximum", ["最大"], 3, "medium"),
    ("pelvic", ["骨盆"], 3, "hard"),
    ("tilt", ["倾斜"], 3, "easy"),
    ("anterior", ["前倾"], 3, "medium"),
    ("posterior", ["后倾"], 3, "medium"),
    ("lateral", ["侧倾"], 3, "medium"),
    ("rotation", ["旋转"], 3, "medium"),
    ("obliquity", ["倾斜"], 3, "hard"),
    (" Trendelenburg", ["特伦德伦堡征"], 3, "hard"),
    ("gait", ["步态"], 5, "hard"),
    ("analysis", ["分析"], 4, "medium"),
    ("spatiotemporal", ["时空"], 3, "hard"),
    ("parameter", ["参数"], 3, "medium"),
    ("cadence", ["步频"], 4, "hard"),
    ("step", ["步"], 5, "easy"),
    ("length", ["长度"], 4, "easy"),
    ("width", ["宽度"], 4, "easy"),
    ("time", ["时间"], 4, "easy"),
    ("stance", ["支撑相"], 4, "hard"),
    ("swing", ["摆动相"], 4, "easy"),
    ("phase", ["相位"], 4, "medium"),
    ("double", ["双"], 4, "easy"),
    ("support", ["支撑"], 4, "easy"),
    ("single", ["单"], 4, "easy"),
    ("limb", ["肢体"], 4, "easy"),
    ("support", ["支撑"], 4, "easy"),
    ("loading", ["负荷"], 4, "medium"),
    ("response", ["反应"], 4, "medium"),
    ("foot", ["足"], 5, "easy"),
    ("strike", ["触地"], 4, "medium"),
    ("pattern", ["模式"], 4, "easy"),
    ("rearfoot", ["后足"], 4, "hard"),
    ("midfoot", ["中足"], 4, "hard"),
    ("forefoot", ["前足"], 4, "hard"),
    ("heel", ["足跟"], 5, "easy"),
    ("toe", ["趾"], 4, "easy"),
    ("strike", ["触地"], 4, "medium"),
    ("pronation", ["旋前"], 4, "hard"),
    ("supination", ["旋后"], 4, "hard"),
    ("eversion", ["外翻"], 4, "hard"),
    ("inversion", ["内翻"], 4, "hard"),
    ("tibial", ["胫骨"], 4, "hard"),
    ("rotation", ["旋转"], 4, "medium"),
    ("internal", ["内旋"], 4, "medium"),
    ("knee", ["膝"], 5, "easy"),
    ("valgus", ["外翻"], 4, "hard"),
    ("varus", ["内翻"], 4, "hard"),
    ("collapse", ["塌陷"], 4, "medium"),
    ("hip", ["髋"], 5, "easy"),
    ("adduction", ["内收"], 4, "hard"),
    ("drop", ["下落"], 4, "easy"),
    ("trunk", ["躯干"], 5, "medium"),
    ("lean", ["前倾"], 4, "easy"),
    ("arm", ["臂"], 5, "easy"),
    ("swing", ["摆动"], 4, "easy"),
    ("opposite", ["对侧"], 4, "medium"),
    ("co-contraction", ["协同收缩"], 3, "hard"),
    ("antagonist", ["拮抗肌"], 3, "hard"),
    ("cross-education", ["交叉教育"], 3, "hard"),
    ("bilateral", ["双侧"], 3, "hard"),
    ("transfer", ["转移"], 3, "medium"),
    ("mirror", ["镜像"], 3, "easy"),
    ("therapy", ["治疗"], 3, "medium"),
    ("action", ["动作"], 3, "easy"),
    ("observation", ["观察"], 3, "medium"),
    ("motor", [" motor", "镜像神经元"], 3, "hard"),
    ("imagery", ["表象"], 3, "hard"),
    ("visualization", ["可视化"], 3, "hard"),
    ("mental", ["心理的"], 3, "medium"),
    ("practice", ["练习"], 3, "medium"),
    ("internal", ["内部"], 3, "medium"),
    ("external", ["外部"], 3, "medium"),
    ("focus", ["焦点"], 3, "medium"),
    ("attention", ["注意"], 3, "medium"),
    ("constrained", ["约束"], 3, "hard"),
    ("action", ["动作"], 3, "easy"),
    ("hypothesis", ["假说"], 3, "hard"),
    ("dynamical", ["动态"], 3, "hard"),
    ("systems", ["系统"], 3, "easy"),
    ("theory", ["理论"], 3, "easy"),
    ("ecological", ["生态"], 3, "hard"),
    ("dynamics", ["动力学"], 3, "hard"),
    ("repetition", ["重复"], 3, "medium"),
    ("without", ["没有"], 3, "easy"),
    ("repetition", ["重复"], 3, "medium"),
    ("RPE", ["主观疲劳程度"], 3, "hard"),
    ("OMNI", ["OMNI量表"], 3, "hard"),
    ("CR-10", ["CR-10量表"], 3, "hard"),
    ("Borg", ["博格"], 3, "hard"),
    ("6-20", ["6-20量表"], 3, "hard"),
    ("0-10", ["0-10量表"], 3, "hard"),
    ("clamped", ["钳制"], 3, "hard"),
    ("feedback", ["反馈"], 3, "medium"),
    ("knowledge", ["知识"], 3, "easy"),
    ("results", ["结果"], 3, "easy"),
    ("KR", ["结果认识"], 3, "hard"),
    ("knowledge", ["知识"], 3, "easy"),
    ("performance", ["表现"], 3, "medium"),
    ("KP", ["表现认识"], 3, "hard"),
    ("bandwidth", ["带宽"], 3, "hard"),
    ("fading", ["渐隐"], 3, "hard"),
    ("summary", ["总结"], 3, "easy"),
    ("average", ["平均"], 3, "easy"),
    ("performance", ["表现"], 3, "medium"),
    ("schema", ["图式"], 3, "hard"),
    ("theory", ["理论"], 3, "easy"),
    ("generalized", ["泛化"], 3, "hard"),
    ("motor", [" motor", "运动程序"], 3, "hard"),
    ("program", ["程序"], 3, "medium"),
    ("GMP", ["泛化运动程序"], 3, "hard"),
    ("motor", [" motor", "参数"], 3, "hard"),
    ("program", ["程序"], 3, "medium"),
    ("recall", ["回忆"], 3, "medium"),
    ("recognition", ["识别"], 3, "medium"),
    ("contextual", ["情境"], 3, "hard"),
    ("interference", ["干扰"], 3, "hard"),
    ("transfer", ["迁移"], 3, "medium"),
    ("negative", ["负"], 3, "medium"),
    ("positive", ["正"], 3, "medium"),
    ("bilateral", ["双侧"], 3, "hard"),
    ("transfer", ["迁移"], 3, "medium"),
    ("variable", ["变化"], 3, "medium"),
    ("practice", ["练习"], 3, "medium"),
    ("constant", ["恒定"], 3, "medium"),
    ("practice", ["练习"], 3, "medium"),
    ("blocked", ["集中"], 3, "medium"),
    ("practice", ["练习"], 3, "medium"),
    ("random", ["随机"], 3, "medium"),
    ("practice", ["练习"], 3, "medium"),
    ("serial", ["序列"], 3, "medium"),
    ("practice", ["练习"], 3, "medium"),
    ("contextual", ["情境"], 3, "hard"),
    ("interference", ["干扰"], 3, "hard"),
    ("elaboration", ["精细加工"], 3, "hard"),
    ("hypothesis", ["假说"], 3, "hard"),
    ("implicit", ["内隐"], 3, "hard"),
    ("explicit", ["外显"], 3, "hard"),
    ("learning", ["学习"], 3, "easy"),
    ("autonomous", ["自动化"], 3, "hard"),
    ("associative", ["联结"], 3, "hard"),
    ("cognitive", ["认知"], 3, "hard"),
    (" Fitts", ["菲茨"], 3, "hard"),
    ("Posner", ["波斯纳"], 3, "hard"),
    ("three-stage", ["三阶段"], 3, "hard"),
    ("model", ["模型"], 3, "medium"),
    ("Gentile", ["金蒂尔"], 3, "hard"),
    ("two-stage", ["两阶段"], 3, "hard"),
    ("model", ["模型"], 3, "medium"),
    ("Bernstein", ["伯恩斯坦"], 3, "hard"),
    ("degrees", ["自由度"], 3, "easy"),
    ("freedom", ["自由"], 3, "easy"),
    ("DOF", ["自由度"], 3, "hard"),
    ("problem", ["问题"], 3, "easy"),
    ("perception-action", ["知觉-动作"], 3, "hard"),
    ("coupling", ["耦合"], 3, "hard"),
    ("affordance", [" affordance", "功能可供性"], 3, "hard"),
    ("Gibson", ["吉布森"], 3, "hard"),
    ("calibration", ["校准"], 3, "hard"),
    ("prospective", ["前瞻"], 3, "hard"),
    ("control", ["控制"], 3, "medium"),
    ("tau", ["τ"], 3, "hard"),
    ("margin", [" margin", "边缘"], 3, "easy"),
    ("stability", ["稳定"], 3, "hard"),
    ("time-to-contact", ["接触时间"], 3, "hard"),
    ("tau-dot", ["τ点"], 3, "hard"),
    ("postural", ["姿势"], 3, "hard"),
    ("control", ["控制"], 3, "medium"),
    ("equilibrium", ["平衡"], 3, "hard"),
    ("point", ["点"], 3, "easy"),
    ("COP", ["压力中心"], 3, "hard"),
    ("COM", ["质心"], 3, "hard"),
    ("stabilogram", ["稳定图"], 3, "hard"),
    ("diffusion", ["扩散"], 3, "hard"),
    ("analysis", ["分析"], 3, "medium"),
    ("Romberg", ["龙贝格"], 3, "hard"),
    ("test", [" test"], 3, "easy"),
    ("Sharpened", [" sharpened", " sharpened"], 3, "hard"),
    ("Romberg", ["龙贝格"], 3, "hard"),
    ("tandem", ["串联"], 3, "medium"),
    ("stance", ["支撑"], 3, "easy"),
    ("single-leg", ["单腿"], 3, "hard"),
    ("stance", ["支撑"], 3, "easy"),
    ("BESS", ["平衡误差评分系统"], 3, "hard"),
    ("Sway", ["摇摆"], 3, "easy"),
    ("sensory", ["感觉"], 3, "hard"),
    ("organization", ["组织"], 3, "medium"),
    ("test", [" test"], 3, "easy"),
    ("SOT", ["感觉组织测试"], 3, "hard"),
    ("CTSIB", ["临床感觉统合测试"], 3, "hard"),
    ("Fukuda", ["福田"], 3, "hard"),
    ("stepping", ["踏步"], 3, "easy"),
    ("test", [" test"], 3, "easy"),
    ("vestibular", ["前庭"], 3, "hard"),
    ("ocular", ["眼"], 3, "hard"),
    ("motor", [" motor", "运动"], 3, "hard"),
    ("VOR", ["前庭眼反射"], 3, "hard"),
    ("vestibulo-ocular", ["前庭眼"], 3, "hard"),
    ("reflex", ["反射"], 3, "medium"),
    ("vestibulospinal", ["前庭脊髓"], 3, "hard"),
    ("reflex", ["反射"], 3, "medium"),
    ("righting", ["翻正"], 3, "hard"),
    ("reflex", ["反射"], 3, "medium"),
    ("tilting", ["倾斜"], 3, "easy"),
    ("reflex", ["反射"], 3, "medium"),
    ("placing", ["放置"], 3, "easy"),
    ("hopping", ["跳跃"], 3, "easy"),
    ("proprioceptive", ["本体感觉"], 3, "hard"),
    ("reweighting", ["重新加权"], 3, "hard"),
    ("sensory", ["感觉"], 3, "hard"),
    ("reweighting", ["重新加权"], 3, "hard"),
    ("reintegration", ["再整合"], 3, "hard"),
    ("multisensory", ["多感觉"], 3, "hard"),
    ("dizziness", ["头晕"], 3, "medium"),
    ("vertigo", ["眩晕"], 3, "hard"),
    ("BPPV", ["良性阵发性位置性眩晕"], 3, "hard"),
    ("Epley", ["埃普利"], 3, "hard"),
    ("maneuver", ["手法"], 3, "medium"),
    ("Semont", ["塞蒙特"], 3, "hard"),
    ("liberatory", [" liberatory", "解放"], 3, "hard"),
    ("maneuver", ["手法"], 3, "medium"),
    ("Brandt-Daroff", ["布兰特-达罗夫"], 3, "hard"),
    ("exercises", ["练习"], 3, "easy"),
    ("canalith", ["耳石"], 3, "hard"),
    ("repositioning", ["复位"], 3, "hard"),
    ("procedure", ["程序"], 3, "medium"),
    ("CRP", ["耳石复位程序"], 3, "hard"),
    ("habituation", ["习惯化"], 3, "hard"),
    ("adaptation", ["适应"], 3, "medium"),
    ("compensation", ["代偿"], 3, "medium"),
    ("substitution", ["替代"], 3, "medium"),
    ("vestibular", ["前庭"], 3, "hard"),
    ("rehabilitation", ["康复"], 3, "hard"),
    ("gaze", ["凝视"], 3, "medium"),
    ("stabilization", ["稳定"], 3, "hard"),
    ("exercise", ["练习"], 3, "easy"),
    ("X", ["X"], 3, "easy"),
    ("Y", ["Y"], 3, "easy"),
    ("Z", ["Z"], 3, "easy"),
    ("target", ["目标"], 3, "easy"),
    ("gaze", ["凝视"], 3, "medium"),
    ("stabilization", ["稳定"], 3, "hard"),
    ("optokinetic", ["视动"], 3, "hard"),
    ("training", ["训练"], 3, "easy"),
    ("OKN", ["视动性眼震"], 3, "hard"),
    ("smooth", ["平滑"], 3, "easy"),
    ("pursuit", ["追踪"], 3, "hard"),
    ("saccade", ["扫视"], 3, "hard"),
    ("vergence", ["聚散"], 3, "hard"),
    ("accommodation", ["调节"], 3, "hard"),
    ("vergence", ["聚散"], 3, "hard"),
    ("accommodative", ["调节性"], 3, "hard"),
    ("vergence", ["聚散"], 3, "hard"),
    ("vergence", ["聚散"], 3, "hard"),
    ("fusional", ["融合性"], 3, "hard"),
    ("vergence", ["聚散"], 3, "hard"),
    ("disparity", ["视差"], 3, "hard"),
    ("stereopsis", ["立体视觉"], 3, "hard"),
    ("binocular", ["双眼"], 3, "hard"),
    ("depth", ["深度"], 3, "easy"),
    ("perception", ["知觉"], 3, "medium"),
    ("monocular", ["单眼"], 3, "hard"),
    ("cue", ["线索"], 3, "easy"),
    ("motion", ["运动"], 3, "easy"),
    ("parallax", ["视差"], 3, "hard"),
    ("looming", ["逼近"], 3, "hard"),
    ("time-to-contact", ["接触时间"], 3, "hard"),
    ("perception", ["知觉"], 3, "medium"),
    ("action", ["动作"], 3, "easy"),
    ("coupling", ["耦合"], 3, "hard"),
    ("tau", ["τ"], 3, "hard"),
    ("ecological", ["生态"], 3, "hard"),
    ("approach", ["方法"], 3, "medium"),
    ("embodied", ["具身"], 3, "hard"),
    ("cognition", ["认知"], 3, "hard"),
    ("extended", ["延展"], 3, "medium"),
    ("mind", ["心智"], 3, "easy"),
    ("distributed", ["分布"], 3, "medium"),
    ("cognition", ["认知"], 3, "hard"),
    ("affordance", ["功能可供性"], 3, "hard"),
    ("direct", ["直接"], 3, "easy"),
    ("perception", ["知觉"], 3, "medium"),
    ("embodied", ["具身"], 3, "hard"),
    ("simulation", ["模拟"], 3, "medium"),
    ("common", ["共同"], 3, "easy"),
    ("coding", ["编码"], 3, "medium"),
    ("mirror", ["镜像"], 3, "easy"),
    ("neuron", ["神经元"], 3, "hard"),
    ("system", ["系统"], 3, "easy"),
]

all_words = physiology + anatomy + cardio + prescription + fitness + nutrition + rehab + biomech + supplement

# 去重：用 word 做 key
words_dict = {}
for word, trans, freq, diff in all_words:
    key = word.lower().strip()
    if key in words_dict:
        continue
    words_dict[key] = {
        "word": word,
        "translations": trans,
        "freq": freq,
        "diff": diff,
        "status": "new",
        "created": 0,
        "example": "",
        "interval": 0,
        "easeFactor": 2.5,
        "due": 0,
        "reviewCount": 0,
        "pdfSource": "ACSM_Glossary_v2"
    }

# 例句（约50个，覆盖高频词）
sentences = [
    {"en": "Resistance training improves muscle strength, hypertrophy, power, and endurance in healthy adults.", "zh": "抗阻训练可提高健康成年人的肌肉力量、肥大、爆发力和耐力。"},
    {"en": "The ACSM recommends at least 150 minutes of moderate-intensity aerobic activity per week.", "zh": "美国运动医学学会建议每周至少进行150分钟中等强度有氧运动。"},
    {"en": "Progressive overload is the gradual increase of stress placed upon the body during exercise training.", "zh": "渐进性超负荷是指在训练过程中逐渐增加对身体的刺激。"},
    {"en": "VO2max is the maximum rate of oxygen consumption measured during incremental exercise.", "zh": "最大摄氧量是在递增运动测试中测得的最高摄氧速率。"},
    {"en": "Muscle hypertrophy refers to the increase in muscle size through resistance training.", "zh": "肌肉肥大是指通过抗阻训练增加肌肉体积。"},
    {"en": "Eccentric contractions produce greater force but cause more muscle damage than concentric contractions.", "zh": "离心收缩产生更大的力量，但比向心收缩造成更多的肌肉损伤。"},
    {"en": "Isokinetic dynamometry provides objective measurements of muscle strength throughout the full range of motion.", "zh": "等速测力计可提供全关节活动范围内肌肉力量的客观测量。"},
    {"en": "The hamstring-to-quadriceps ratio should typically exceed 0.60 to reduce ACL injury risk.", "zh": "腘绳肌/股四头肌比值通常应超过0.60以降低前交叉韧带损伤风险。"},
    {"en": "Delayed onset muscle soreness typically peaks 24 to 72 hours after unaccustomed exercise.", "zh": "延迟性肌肉酸痛通常在不适应运动后24-72小时达到高峰。"},
    {"en": "Blood flow restriction training can produce muscle adaptations at low loads.", "zh": "血流限制训练可在低负荷下产生肌肉适应。"},
    {"en": "Cardiovascular endurance is improved through sustained aerobic activities like running and cycling.", "zh": "心肺耐力通过跑步和骑行等持续性有氧运动得到改善。"},
    {"en": "Periodization involves systematic planning of athletic training through macrocycles, mesocycles, and microcycles.", "zh": "周期化涉及通过大周期、中周期和小周期对运动训练进行系统规划。"},
    {"en": "The Rating of Perceived Exertion scale measures subjective exercise intensity from 6 to 20.", "zh": "主观疲劳程度量表测量6-20级的主观运动强度。"},
    {"en": "MET values represent the ratio of working metabolic rate to resting metabolic rate.", "zh": "代谢当量值表示工作代谢率与静息代谢率的比值。"},
    {"en": "Protein intake of 1.2 to 2.0 grams per kilogram body weight supports muscle protein synthesis.", "zh": "每公斤体重摄入1.2-2.0克蛋白质可支持肌肉蛋白质合成。"},
    {"en": "Dehydration of more than 2% body mass impairs endurance performance and cognitive function.", "zh": "脱水超过体重2%会损害耐力表现和认知功能。"},
    {"en": "The stretch-shortening cycle utilizes elastic energy storage during eccentric loading.", "zh": "牵张-缩短周期利用离心负荷期间的弹性能量储存。"},
    {"en": "Motor unit recruitment follows the size principle, from small to large motor units.", "zh": "运动单位募集遵循大小原则，从小到大依次募集。"},
    {"en": "Sarcopenia is the age-related loss of muscle mass, strength, and function.", "zh": "肌少症是与年龄相关的肌肉质量、力量和功能丧失。"},
    {"en": "The Frank-Starling mechanism describes the relationship between cardiac preload and stroke volume.", "zh": "弗兰克-斯塔林机制描述了心脏前负荷与每搏量之间的关系。"},
    {"en": "Lactate threshold is the exercise intensity where blood lactate begins to accumulate above resting levels.", "zh": "乳酸阈值是指血乳酸开始高于静息水平的运动强度。"},
    {"en": "Anaerobic glycolysis provides rapid ATP production without requiring oxygen.", "zh": "无氧糖酵解可在不需要氧气的情况下快速产生ATP。"},
    {"en": "Flexibility training should include both static and dynamic stretching methods.", "zh": "柔韧性训练应包括静态和动态拉伸方法。"},
    {"en": "The proprioceptive neuromuscular facilitation technique enhances range of motion through contract-relax sequences.", "zh": "本体感觉神经肌肉促进技术通过收缩-放松序列增加关节活动度。"},
    {"en": "Overtraining syndrome results from excessive training load with insufficient recovery.", "zh": "过度训练综合征是由训练负荷过大、恢复不足导致的。"},
    {"en": "Ground reaction force analysis helps assess running mechanics and injury risk.", "zh": "地面反作用力分析有助于评估跑步生物力学和损伤风险。"},
    {"en": "Electromyography measures the electrical activity produced by skeletal muscles during contraction.", "zh": "肌电图测量骨骼肌收缩期间产生的电活动。"},
    {"en": "The stretch reflex is a monosynaptic reflex that protects muscles from overstretching.", "zh": "牵张反射是一种单突触反射，可保护肌肉免受过度拉伸。"},
    {"en": "Agonist and antagonist muscles work together to produce coordinated movement.", "zh": "主动肌和拮抗肌协同工作以产生协调运动。"},
    {"en": "Core stability is essential for transferring force between the upper and lower extremities.", "zh": "核心稳定性对于上下肢之间的力量传递至关重要。"},
    {"en": "High-intensity interval training produces similar cardiovascular adaptations to moderate continuous training in less time.", "zh": "高强度间歇训练在更短时间内产生与中等强度持续训练相似的心血管适应。"},
    {"en": "The RICE principle (Rest, Ice, Compression, Elevation) is used for acute soft tissue injury management.", "zh": "RICE原则（休息、冰敷、加压、抬高）用于急性软组织损伤处理。"},
    {"en": "Joint proprioception can be impaired after ligament injury and requires rehabilitation.", "zh": "韧带损伤后关节本体感觉可能受损，需要进行康复训练。"},
    {"en": "Functional movement screening identifies movement limitations and asymmetries before training.", "zh": "功能性动作筛查可在训练前识别动作受限和不对称。"},
    {"en": "Exercise adherence is improved when programs are tailored to individual preferences and goals.", "zh": "当运动方案根据个人偏好和目标量身定制时，依从性会提高。"},
    {"en": "Basal metabolic rate accounts for approximately 60-75% of total daily energy expenditure.", "zh": "基础代谢率约占每日总能量消耗的60-75%。"},
    {"en": "The phosphocreatine system provides immediate energy for high-intensity activities lasting up to 10 seconds.", "zh": "磷酸肌酸系统为持续10秒以内的高强度活动提供即时能量。"},
    {"en": "Type II muscle fibers are characterized by high force production but rapid fatigue.", "zh": "II型肌纤维的特点是力量产生大但疲劳快。"},
    {"en": "Osteoporosis prevention requires weight-bearing and resistance exercises to stimulate bone formation.", "zh": "骨质疏松预防需要进行负重和抗阻运动以刺激骨形成。"},
    {"en": "Balance training reduces fall risk in older adults by improving postural control.", "zh": "平衡训练通过改善姿势控制降低老年人跌倒风险。"},
    {"en": "Myocardial oxygen demand increases with heart rate, contractility, and wall tension.", "zh": "心肌氧需求随心率、收缩力和室壁张力增加而增加。"},
    {"en": "Ventilatory threshold represents the point where ventilation increases disproportionately to oxygen uptake.", "zh": "通气阈值代表通气量相对于摄氧量不成比例增加的点。"},
    {"en": "Sport-specific training should mimic the biomechanical and metabolic demands of competition.", "zh": "专项训练应模拟比赛的生物力学和代谢需求。"},
    {"en": "Tendinopathy management includes eccentric loading exercises and load management.", "zh": "肌腱病管理包括离心负荷练习和负荷管理。"},
    {"en": "The kinetic chain concept describes how movement in one joint affects adjacent segments.", "zh": "动力链概念描述了某个关节的运动如何影响相邻节段。"},
    {"en": "Post-exercise nutrition timing within 30-60 minutes optimizes glycogen resynthesis.", "zh": "运动后30-60分钟内的营养补充可优化糖原再合成。"},
    {"en": "Adaptation to training occurs during recovery periods, not during the training itself.", "zh": "训练适应发生在恢复期，而非训练期间本身。"},
    {"en": "Motor learning principles include repetition, specificity, feedback, and progressive difficulty.", "zh": "运动学习原则包括重复性、专门性、反馈和渐进难度。"},
    {"en": "The stretch-shortening cycle is critical for explosive movements like jumping and sprinting.", "zh": "牵张-缩短周期对于跳跃和冲刺等爆发力动作至关重要。"},
    {"en": "Closed kinetic chain exercises are generally preferred for functional rehabilitation.", "zh": "闭链运动通常是功能性康复的首选。"},
]

# 构建输出
output = {
    "words": words_dict,
    "sentences": sentences,
    "settings": {
        "dailyNew": 10,
        "dailyReview": 30,
        "autoSpeak": "off",
        "showImage": "on",
        "translateEngine": "mymemory",
        "extractCount": 1000
    },
    "studyLog": [],
    "pdfSource": "ACSM_Glossary_v2"
}

# 生成 prebuilt.js
js_content = "const PREBUILT_VOCAB=" + json.dumps(output, ensure_ascii=False, separators=(',', ':')) + ";\nwindow.PREBUILT_VOCAB=PREBUILT_VOCAB;"

with open("/root/.openclaw/workspace/vocabulary-builder/prebuilt.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"生成完成: {len(words_dict)} 个单词, {len(sentences)} 条例句")
print(f"文件大小: {len(js_content)} 字节 ({len(js_content)/1024:.1f} KB)")
